### ISSUE TITLE
A bug that was filed in nats.go

### ISSUE THREAD

**Issue by idc77** [nats-io/natscli#1005]
### Observed behavior

please see https://github.com/nats-io/nats.go/issues/1561
I created the bug report in the wrong repository, I didn't see the natscli repo.

### Expected behavior

^ 

### Server and client version

^

**Comment by ripienaar** [comment]
We will do a CLI release soon that bumps to next nats.go. Just waiting for server to complete its release also.

**Comment by 1995parham** [comment]
Thanks, @ripienaar. I will update the AUR package right after the release.
