### ISSUE TITLE
nats: error: could not select Stream: invalid character '+' looking for beginning of value

### ISSUE THREAD

**Issue by sourcec0de** [nats-io/natscli#102]
## Reproduction steps

Start NATS
```shell
docker run -ti -p 4222:4222 --name jetstream synadia/jsm@sha256:505dcdeb6752fb6ec88ef5b905e9c4e0b9ff55dee4f219eebb43ae5c9ae64159 server
```

Create a new stream with the subject filter set to `>` and all the default options
```shell
nats stream add BUG --subjects=">"
```

Running  `nats consumer` or `nats stream` commands returns an error
```shell
nats stream info --trace
```

```text
19:24:23 >>> $JS.API.STREAM.NAMES
{"offset":0}

19:24:23 <<< $JS.API.STREAM.NAMES
+OK {"stream": "BUG", "seq": 13}

nats: error: could not pick a Stream to operate on: invalid character '+' looking for beginning of value
```

Once this is done you cannot `rm` the offending stream.

**Comment by ripienaar** [comment]
You cannot make a stream with subjects “>”

that will ingest into it many unrelated messages, including as is happening here the API requests. 

What you are seeing is the ACk that the API request was stored before the API response 

you need to make streams with only just what you need.

**Comment by sourcec0de** [comment]
@ripienaar I understand that the use of `>` as a subject filter would create a stream that would ingest all messages. That was actually the intention. 

If this is should be considered an illegal operation the server should have rejected this. The fact remains that under these circumstances a user can render the jetstream subcommands inoperable by running this command `nats stream add BUG --subjects=">"`.

Would you please consider reopening this?

**Comment by ripienaar** [comment]
Will add a check. But successfully checking for any subject that can cause trouble is simply not possible as to a large extend it depends on your environment.

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/103

**Comment by sourcec0de** [comment]
@ripienaar thank you!
This was a really awesome turn around time.
