### ISSUE TITLE
corrupt images when headers data is included

### ISSUE THREAD

**Issue by parasaliPNG** [nats-io/natscli#1085]
### Observed behavior

while using object store with python, when we add headers onto our image objects, we cannot use the nats cli to view the bucket. it says that the image is corrupt. has anyone encountered this? putting the images and pulling via python from the bucket still works but nothing through the cli.

### Expected behavior

The nats cli should operate with and without header data. 

### Server and client version

nats-server: v2.10.12
nats --version 0.1.4

### Host environment

Windows 10 IoT Enterprise LTSC
12th Gen Intel(R) Core(TM) i5-12500E   2.90 GHz

### Steps to reproduce

add json object as a header to the images
push onto the bucket 
try to view/subscribe/watch the bucket through the cli, it should fail to provide the requested info, 

if bucket is cleared, and the same image is added without header, the cli should operate as expected.

**Comment by ripienaar** [comment]
Can you please show the actual errors you get?

**Comment by parasaliPNG** [comment]
![image (26)](https://github.com/nats-io/natscli/assets/70565454/3f3b0cb6-c397-4c1d-99b5-e7aa05370992)
![image (26)](https://github.com/nats-io/natscli/assets/70565454/3f3b0cb6-c397-4c1d-99b5-e7aa05370992)



this is the error

**Comment by ripienaar** [comment]
thanks, can you please pass --trace to the command and show that alow

**Comment by ripienaar** [comment]
The error is from nats.go so the issue should go there but lets see perhaps the python library put something bad

**Comment by ripienaar** [comment]
Closing, feel free to re-open when you have additional data
