### ISSUE TITLE
Failed to resolve requested version when downloading nats-cli binary

### ISSUE THREAD

**Issue by jamm3e3333** [nats-io/natscli#1087]
### Observed behavior

I'm trying to download nats-cli binary like this `curl -sf https://binaries.nats.dev/nats-io/natscli/nats@latest | sh` as one of the recommended methods of downloading the nats-cli, but everytime I try it says:

```
Failed to resolve requested version
```

I tried even for different versions v0.1.4 (latest), v0.1.3.

### Expected behavior

Downloading the nats-cli binary

### Server and client version

I don't think in this case the nats server version is relevant, as I don't have a problem with executing the nats-cli for the nats-server

### Host environment

mac OS M2 arm64, but mainly I wanna run the nats-cli in a docker-container from this image:

```
FROM bash:latest
...
```

### Steps to reproduce

running bash docker container with downloading the nast-cli binary

```Docker
FROM bash:latest

RUN apk add --no-cache curl

CMD ["setup-nats.sh"]
```

setup-nats.sh
```sh
#!/usr/bin/env bash
set -euo pipefail

curl -sf https://binaries.nats.dev/nats-io/natscli/nats@latest | sh && mv nats /usr/local/bin/

nats --version
```

**Comment by ripienaar** [comment]
Hmm, not sure who owns the binaries service maybe @wallyqs or @philpennock has some ideas?

**Comment by wallyqs** [comment]
I think this should be resolved now.

**Comment by jamm3e3333** [comment]
will try, thanks

**Comment by jamm3e3333** [comment]
It works, thank you @wallyqs may I know what was the issue?

**Comment by sjwl** [comment]
it's back
```
curl --no-progress-meter https://binaries.nats.dev/nats-io/natscli/nats@v0.1.5 > ~/tmp/natscli.sh
cat ~/tmp/natscli.sh
echo
printf "  \033[38;5;125mError:\033[0;00m Failed to resolve requested version\n"
echo
exit 1
```

**Comment by jamm3e3333** [comment]
> it's back
> 
> ```
> curl --no-progress-meter https://binaries.nats.dev/nats-io/natscli/nats@v0.1.5 > ~/tmp/natscli.sh
> cat ~/tmp/natscli.sh
> echo
> printf "  \033[38;5;125mError:\033[0;00m Failed to resolve requested version\n"
> echo
> exit 1
> ```
> 
> Workaround: retry

it seems that it's working now

**Comment by bkochauri-memphis** [comment]
Hi 
It looks like the issue with the install script still persists:
`curl -sf https://binaries.nats.dev/nats-io/natscli/nats@latest | sh
`
It returns:
`Error: Failed to resolve requested version`

Could you please take another look? Thanks!

**Comment by ripienaar** [comment]
Please download from github. That’s the only method I can support.
