### ISSUE TITLE
The command 'nats server check consumer' doesn't work

### ISSUE THREAD

**Issue by senglory** [nats-io/natscli#1099]
### Observed behavior

Here's my cmd line prompt:

> PS C:\tmp> nats server check consumer
> error: expected command but got "consumer", use --help for full help including flags and arguments
> 
> usage: nats server check [<flags>] <command> [<args> ...]
> 
> Health check for NATS servers
> 
> Subcommands:
>   server check connection  Checks basic server connection
>   server check stream      Checks the health of mirrored streams, streams with
>                            sources or clustered streams
>   server check message     Checks properties of a message stored in a stream
>   server check meta        Check JetStream cluster state
>   server check jetstream   Check JetStream account state
>   server check server      Checks a NATS Server health
>   server check kv          Checks a NATS KV Bucket
>   server check credential  Checks the validity of a NATS credential file
> 
> Flags:
>   --format=nagios    Render the check in a specific format (nagios, json,
>                      prometheus, text)
>   --namespace="nats_server_check"
>                      The prometheus namespace to use in output
>   --outfile=OUTFILE  Save output to a file rather than STDOUT
> 
> Pass --help to see global flags applicable to this command.

### Expected behavior

It should work as described in the spec

### Server and client version

nats --version shows 0.1.4

### Host environment

Windows 10 x64 22H2

**Comment by ripienaar** [comment]
It is not yet released, but will be in this week.

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/releases/tag/v0.1.5
