### ISSUE TITLE
Please allow installation by go install

### ISSUE THREAD

**Issue by tpihl** [nats-io/natscli#116]
go install github.com/nats-io/natscli/nats 

is failing because of replace statement in go.mod. Could the actual import statement be changed instead?

**Comment by ripienaar** [comment]
No, unfortunately its github.com/tylertreat/hdrhistogram-writer that uses a old module name, we'd love to update, but its not our code thats the issue.

go mod is a mess, GIGO.

**Comment by ripienaar** [comment]
See note about go mod beinga mess :)

```
$ go mod vendor
$ grep -r github.com/codahale/hdrhistogram vendor
...
vendor/github.com/tylertreat/hdrhistogram-writer/writer.go:  "github.com/codahale/hdrhistogram"
```
```

**Comment by ripienaar** [comment]
Closing this, its a bit out of my control unfortunately
