### ISSUE TITLE
nagios-style check for jetstream responder found

### ISSUE THREAD

**Issue by philpennock** [nats-io/natscli#168]
The `nats server check connection` mode is really helpful.  I'd like a Jetstream equivalent.

If I can supply a context or creds for a monitoring account, and also `--js-domain`, as I can now, to target which jetstream leafnode I'm talking to, then a `nats` CLI mode which can check for there being a jetstream responder will let me monitor jetstream being "up" and plug this into any NAGIOS-compatible setup.

A bonus would be if it can take the max available space for disk/mem and the used space and transition into warning state if the available space is less than a given percentage (CLI-overrideable in the usual manner).

**Comment by ripienaar** [comment]
Sounds to me like these are the same - account info end point will tell us its up and also the metrics, so seems I can combine them into one.

Good idea, will add.

**Comment by ripienaar** [comment]
```
$ nats server check js --help
...
      --mem-warn=75             Warning threshold for memory storage, in percent
      --mem-critical=90         Critical threshold for memory storage, in percent
      --store-warn=75           Warning threshold for disk storage, in percent
      --store-critical=90       Critical threshold for memory storage, in percent
      --streams-warn=-1         Warning threshold for number of streams used, in percent
      --streams-critical=-1     Critical threshold for number of streams used, in percent
      --consumers-warn=-1       Warning threshold for number of consumers used, in percent
      --consumers-critical=-1   Critical threshold for number of consumers used, in percent
```

Merged in https://github.com/nats-io/natscli/pull/169
