### ISSUE TITLE
feature: context validation

### ISSUE THREAD

**Issue by philpennock** [nats-io/natscli#18]
When copying contexts between systems and wanting to make sure I have everything right, I find I want `nats context validate` or `nats context ls --check` or something like that.

For each context (ideally), validate that all referenced file-paths exist and are not empty.

The `ls --check` approach would clearly be validate all of them.  Perhaps `nats context validate` should just validate the one, unless `--all` is given.

Bonus feature: `nats context validate --all --test-connect` -- open connections to the NATS servers and authenticate, before dropping the connection.

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/19

**Comment by ripienaar** [comment]
Put a basic feature in - show will validate, and you can pass --connect to show, also added validate that can do all.  I think I like the `ls` option, will add that too just forgot about it while implementing
