### ISSUE TITLE
Jetstream bench publisher ack timeout for publishAsync batch is 1 second

### ISSUE THREAD

**Issue by vishaltripathi24** [nats-io/natscli#230]
Get the error : `JS PubAsync did not receive a positive ack while running nats bench for jetstream `

Command. : nats bench test --js --pub 10 --msgs 1000000 --pubbatch 1500 --size 100 --storage file --replicas 3

`11:57:13 Starting benchmark [msgs=1,000,000, msgsize=100 B, pubs=10, subs=0, js=true, storage=file, syncpub=false, pubbatch=1,500, pull=false, pullbatch=100, request=false, reply=false, noqueue=false, maxackpending=-1, replicas=3, nopurge=false, nodelete=false]
11:57:13 Deleting any existing stream
11:57:13 Purging the stream
11:57:13 Will delete the stream at the end of the run
   0s [>---------------------------------------------------------]   4%
   0s [>---------------------------------------------------------]   4%
   1s [=>--------------------------------------------------------]   6%
   1s [=>--------------------------------------------------------]   6%
   1s [=>--------------------------------------------------------]   6%
   1s [>---------------------------------------------------------]   4%
   1s [=>--------------------------------------------------------]   6%
   1s [=>--------------------------------------------------------]   6%
   1s [=>--------------------------------------------------------]   6%
   1s [>---------------------------------------------------------]   4%

11:57:15 JS PubAsync did not receive a positive ack`

**Comment by vishaltripathi24** [comment]
@jnmoyne I tried with new changes and now I see bench not exiting even though all pub-sub complete 100%.. the subs stay in receiving state thereafter.
Using NATS server 2.3.4

`nats bench testsubject --pub=5 --sub=10 --js --storage=file --msgs=1000000 --size=500 --pubbatch=100
10:12:16 Starting benchmark [msgs=1,000,000, msgsize=500 B, pubs=5, subs=10, js=true, storage=file, syncpub=false, pubbatch=100, pubtimeout=30s, pull=false, pullbatch=100, request=false, reply=false, noqueue=false, maxackpending=-1, replicas=1, nopurge=false, nodelete=false]
10:12:16 Deleting any existing benchstream stream
10:12:16 Purging the stream
10:12:16 Will delete the stream benchstream at the end of the run
10:12:16 Starting subscriber, expecting 1,000,000 messages
10:12:16 Starting subscriber, expecting 1,000,000 messages
10:12:16 Starting subscriber, expecting 1,000,000 messages
10:12:16 Starting subscriber, expecting 1,000,000 messages
10:12:16 Starting subscriber, expecting 1,000,000 messages
10:12:16 Starting subscriber, expecting 1,000,000 messages
10:12:16 Starting subscriber, expecting 1,000,000 messages
10:12:16 Starting subscriber, expecting 1,000,000 messages
10:12:16 Starting subscriber, expecting 1,000,000 messages
10:12:16 Starting subscriber, expecting 1,000,000 messages
Receiving   1m1s [==================================================================================================================================>] 100%
Finished    1m1s [===================================================================================================================================] 100%
Finished    1m1s [===================================================================================================================================] 100%
Finished    1m1s [===================================================================================================================================] 100%
Finished    1m1s [===================================================================================================================================] 100%
Receiving   1m1s [==================================================================================================================================>] 100%
Receiving   1m1s [==================================================================================================================================>] 100%
Finished    1m1s [===================================================================================================================================] 100%
Receiving   1m1s [==================================================================================================================================>] 100%
Finished    1m1s [===================================================================================================================================] 100%
Finished    1m0s [===================================================================================================================================] 100%
Finished    1m0s [===================================================================================================================================] 100%
Finished    1m1s [===================================================================================================================================] 100%
Finished    1m0s [===================================================================================================================================] 100%
Finished     59s [===================================================================================================================================] 100%`

**Comment by jnmoyne** [comment]
For this last comment above: the problem with push consumers sometimes not finishing has been identified and is a different problem that the JS ack timeout issue this issue was created about. The problem in question has been identified and is not related to natscli. nats-server 2.4.1 will fix that issue.
