### ISSUE TITLE
nats-box is out of date

### ISSUE THREAD

**Issue by coder543** [nats-io/natscli#263]
The `synadia/nats-box` image seems to be on a 6+ month old version of this tool, so I installed the latest release manually on my machine to have the new features (like the experimental KV store). Just figured I would mention this here in case `nats-box` is still being maintained.

**Comment by ripienaar** [comment]
@wallyqs whats the process for updating nats-box? Is it automated at all?

**Comment by ripienaar** [comment]
I am not sure whats up with nats-box but I heard its perhaps being deprecated, eitherway this is an issue for the nats-box project so will close this one.
