### ISSUE TITLE
nats stream info json reply

### ISSUE THREAD

**Issue by kino71** [nats-io/natscli#28]
I defined a stream with 

    nats add stream: 

             Subjects: GS.>, QS.>, TSM.UPDATE.>, LM.>
       Acknowledgements: true
              Retention: File - Limits
               Replicas: 1
         Discard Policy: Old
       Duplicate Window: 10m0s
       Maximum Messages: unlimited
          Maximum Bytes: unlimited
            Maximum Age: 1d0h0m0s
     Maximum Message Size: unlimited
       Maximum Consumers: unlimited
     State:
              Messages: 30
                 Bytes: 1.6 KiB
              FirstSeq: 1 @ 2021-01-16T13:59:58 UTC
               LastSeq: 30 @ 2021-01-16T14:21:46 UTC
     Active Consumers: 1

and exported the json definition with "nats stream info [stream] -j" 
The resulting json was:

      {
        "config": {
          "name": "MERCURY",
          "subjects": [
            "GS.\u003e",
            "QS.\u003e",
            "TSM.UPDATE.\u003e",
            "LM.\u003e"
          ],
          "retention": "limits",
          "max_consumers": -1,
          "max_msgs": -1,
          "max_bytes": -1,
          "max_age": 86400000000000,
          "max_msg_size": -1,
          "storage": "file",
          "discard": "old",
          "num_replicas": 1,
          "duplicate_window": 600000000000
        },
        "state": {
          "messages": 30,
          "bytes": 1683,
          "first_seq": 1,
          "first_ts": "2021-01-16T13:59:58.985443012Z",
          "last_seq": 30,
          "last_ts": "2021-01-16T14:21:46.635100851Z",
          "consumer_count": 1
        }
      }

If I try to edit something (or nothing at all) and run:

    nats stream edit MERCURY --config mercury_stream.json

There are many unexpected differences found :

     Differences (-old +new):
      api.StreamConfig{
            Name:         "MERCURY",
    -       Subjects:     []string(Inverse(Sort, []string{"GS.>", "LM.>", "QS.>", "TSM.UPDATE.>"})),
    +       Subjects:     []string(Inverse(Sort, []string(nil))),
            Retention:    s"Limits",
    -       MaxConsumers: -1,
    +       MaxConsumers: 0,
    -       MaxMsgs:      -1,
    +       MaxMsgs:      0,
    -       MaxBytes:     -1,
    +       MaxBytes:     0,
    -       MaxAge:       s"24h0m0s",
    +       MaxAge:       s"0s",
    -       MaxMsgSize:   -1,
    +       MaxMsgSize:   0,
            Storage:      s"File",
            Discard:      s"Old",
    -       Replicas:     1,
    +       Replicas:     0,
            NoAck:        false,
            Template:     "",
    -       Duplicates:   s"10m0s",
    +       Duplicates:   s"0s",
      }

I'll try with 

     nats stream add --output

and report

**Comment by ripienaar** [comment]
I improved these a bit, looks better now, closing

**Comment by mrclki** [comment]
> I improved these a bit, looks better now, closing

Was this fixed?

I get the same kind of result with the newest version `0.0.28`.

**Comment by ripienaar** [comment]
Same kind of display but fewer unexpected changes in things you didn’t change
