### ISSUE TITLE
Binary missing in ZIP files

### ISSUE THREAD

**Issue by palsivertsen** [nats-io/natscli#29]
Downloaded the zip file for the [0.0.21](https://github.com/nats-io/natscli/releases/download/0.0.21/nats-0.0.21-linux-amd64.zip) linux-amd64 release, but looks like it's just a Helm chart and no binary. Is this a mistake or am I missing something?

**Comment by ripienaar** [comment]
Thanks. That’s definitely a bug. Will check it out and fix thanks

**Comment by ripienaar** [comment]
```Archive:  nats-0.0.21-linux-amd64.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
    11357  12-03-2020 11:55   nats-0.0.21-linux-amd64/LICENSE
    19004  12-16-2020 11:35   nats-0.0.21-linux-amd64/README.md
 12853248  01-06-2021 13:10   nats-0.0.21-linux-amd64/nats```

see the last file?
