### ISSUE TITLE
stream report shows system streams without --all flag

### ISSUE THREAD

**Issue by tbeets** [nats-io/natscli#307]
Both stream list and stream report have the -a (--all) option but stream report displays Key-Value streams by default (no --all flag) whereas stream list hides Key-Value streams by default.

Expectation is that stream report would not show Key-Value streams (and other system streams) unless --all flag is included.

```
$ nats stream list
No Streams defined, pass -a to include system streams
$ nats stream report
Obtaining Stream stats

╭─────────────────────────────────────────────────────────────────────────────────╮
│                                  Stream Report                                  │
├────────────┬─────────┬───────────┬──────────┬───────┬──────┬─────────┬──────────┤
│ Stream     │ Storage │ Consumers │ Messages │ Bytes │ Lost │ Deleted │ Replicas │
├────────────┼─────────┼───────────┼──────────┼───────┼──────┼─────────┼──────────┤
│ KV_bucket2 │ File    │ 0         │ 0        │ 0 B   │ 0    │ 0       │ vbox3*   │
│ KV_bucket3 │ File    │ 0         │ 0        │ 0 B   │ 0    │ 0       │ vbox1*   │
│ KV_bucket4 │ File    │ 0         │ 0        │ 0 B   │ 0    │ 0       │ vbox1*   │
│ KV_bucket6 │ File    │ 0         │ 0        │ 0 B   │ 0    │ 0       │ vbox3*   │
│ KV_bucket1 │ File    │ 0         │ 2        │ 94 B  │ 0    │ 0       │ vbox3*   │
╰────────────┴─────────┴───────────┴──────────┴───────┴──────┴─────────┴──────────╯
```

**Comment by ripienaar** [comment]
I am not a fan of these hidden streams. But can see the argument for ls. However for reports that indicate health etc I think we should show them else issues with them are undetectable.

**Comment by ripienaar** [comment]
@tbeets What do you think wrt my reply above? For report I think we should leave them visible.

**Comment by tbeets** [comment]
I agree with your distinction between the two CLI use cases @ripienaar .   Sorry for the tardy reply.
