### ISSUE TITLE
missing `nats consumer events` command

### ISSUE THREAD

**Issue by kung-foo** [nats-io/natscli#328]
Hi, the docs here https://github.com/nats-io/nats.docs/blob/master/using-nats/jetstream/model_deep_dive.md?plain=1#L458 mention an `events` subcommand to `nats consumer` however it doesn't seem to exist.

**Comment by ripienaar** [comment]
Definitely no such command. nats events is all that can show these now. No recollection of consumer events sub command existing :)

**Comment by ripienaar** [comment]
I'll close this one, I think the docs are wrong maybe something @jnmoyne or @gcolliso can fix.  Such a command might be useful but for now no such specialised event viewer exist, only `nats event`

**Comment by jnmoyne** [comment]
I'll look at fixing the docs
