### ISSUE TITLE
improve nats -h

### ISSUE THREAD

**Issue by ripienaar** [nats-io/natscli#330]
As it stands its entirely unusable, so look at writing a short intro style help and just a list of sub commands or something.  We might be bumping up to restrictions in what kingpin allows though.

Longer term we should make the cli implementation extractable so other cli libraries can perhaps be used

**Comment by codegangsta** [comment]
Agree with this. Its one of the first things I noticed when I fired up the cli. Do we have strong opinions on kingpin vs urfave/cli, cobra or ffcli? Happy to take a whack at some conversion

**Comment by codegangsta** [comment]
Another note to add here: I think we should be separating global flags from subcommand specific flags in the helpdocs. It would be nice to be able to filter out all the global options like tls, jetstream and creds. For instance, the `—command` flag in `nats reply` is awesome, but I had a hard time finding it at first (I didn’t actually find it until I read the example :) )

**Comment by ripienaar** [comment]
I definitely have no interest in moving away from kingpin. 

But I might fork kingpin and fix some issues preventing help templates working well enough to fix this problem.

**Comment by codegangsta** [comment]
Makes sense! At this point it probably would be easier to fork kingpin to get better output for `-h`

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/478 improves matters a bit

**Comment by codegangsta** [comment]
Oh awesome! I'll have to check this out.

**Comment by ripienaar** [comment]
Essentially we have this now:

```
usage: nats [<flags>] <command> [<args> ...]

NATS Utility

NATS Server and JetStream administration.

See 'nats cheat' for a quick cheatsheet of commands

Commands:
  account
    Account information and status

  backup [<flags>] <output>
    JetStream configuration backup utility

  bench [<flags>] <subject>
    Benchmark utility

  cheat [<flags>] [<section>]
    Cheatsheets for the nats CLI

  consumer [<flags>]
    JetStream Consumer management

  context
    Manage nats configuration contexts
...
```

So:

 * No common flags in top level help
 * Only 1st lne of command help in top level help
 * No sub sub commands in top level help
 

```
$ nats s add --help
...
      --[no-]trace               Trace API interactions
  -a, --[no-]all                 When listing or selecting streams show all
...
```

Hints on all boolean flags about the `--no-x` version

**Comment by ripienaar** [comment]
@tbeets keen on your thoughts on help behavior of nightly

**Comment by ripienaar** [comment]
Closing this, we did a bunch, but suspect it will be ongoing small piecemeal improvements.
