### ISSUE TITLE
Stream/Consumer command to report number of subscriptions for the same queue group

### ISSUE THREAD

**Issue by rpuppo** [nats-io/natscli#335]
Hello,

I didn't see any command in order to report the number of subscriptions bind to the same consumer and belonging to the same queue group in a stream.

Could you please let me know if it's possible? It could be very useful for investigation and load balancing issues.

BR,
Riccardo

**Comment by ripienaar** [comment]
I do not believe we have that information available

**Comment by rpuppo** [comment]
Are there plan to add that info? I think we could see already something from nats-top utility, isn't it?

**Comment by ripienaar** [comment]
The only way to get it is via the server subscription list endpoint which is not exposed to a normal user account - and even to get the real answer you would have to walk all the account cross connections etc

Where the stream/consumer command do not run at system level, the information is not accessible.
