### ISSUE TITLE
Rename commands for consistency

### ISSUE THREAD

**Issue by DeanPDX** [nats-io/natscli#336]
In most places in the CLI where you can list/detail items, the command to list is `ls` and to show information about a specific item `info`:

```
  account info
  consumer info [<flags>] [<stream>] [<consumer>]
  object info <bucket> [<file>]
  server info [<server>]
  stream info [<flags>] [<stream>]
  stream template info [<flags>] [<template>]
```

It seems intuitive that you would then be able to `ls` then use the `info` command for context and schema, but it's `show` rather than `info`:

```
  context show [<flags>] [<name>]
  schema show [<flags>] <schema>
```

For consistency, consider changing all "display information about x" commands to "info". Similarly, list commands are mostly `ls` but there are a few outliers that are `list` instead:

```
  errors list [<flags>] [<match>] [<sort>]
  kv list [<flags>]
  server list [<flags>] [<expect>]
```

It would be [trivial to change](https://github.com/nats-io/natscli/blob/main/cli/context_command.go#L63) but would be a breaking change and might require maintaining compatibility for a few versions with a deprecation notice.

**Comment by ripienaar** [comment]
We can fix these - we can change them to the new names and add a `Alias()` to the command.

https://github.com/nats-io/natscli/blob/06300613924243f890ff28d9f6f389c9936fe8c0/cli/errors_command.go#L33

So already `ls` work, we can just swap things around so the primary is what shows up in --help, and also so maintain backward compat where we are introducing new names.

Want to give it a go?

**Comment by DeanPDX** [comment]
Sure. I submitted #337 which should address this. Let me know if I missed anything that wouldn't obviously break during the build (for example, I tried to make sure I got all cheat text / readme).
