### ISSUE TITLE
nats cli context 

### ISSUE THREAD

**Issue by aricart** [nats-io/natscli#340]
If I have a context like:
`nsc generate profile nsc://synadia/AA/a` which yields:

```json
{
  "user_creds": "/Users/synadia/.nkeys/creds/synadia/AA/a.creds",
  "operator": {
    "service": [
      "tls://connect.ngs.global"
    ]
  }
}
```

And then try to import that into natscli:
```bash
nats context save AA --nsc=nsc://synadia/AA/a
NATS Configuration Context "AA"

      Server URLs: nats://127.0.0.1:4222
      Credentials: /Users/synadia/.nkeys/creds/synadia/AA/a.creds (OK)
       NSC Lookup: nsc://synadia/AA/a
             Path: /Users/synadia/.config/nats/context/AA.json
```

The server URLs flag for natscli will dominate, so a default is added, but it wrong. If the `--server` is not specified, it shouldn't add it. The default connection should simply not be provided if not specified, which would allow the connect call to default itself.

**Comment by ripienaar** [comment]
fixed via https://github.com/nats-io/jsm.go/pull/355
