### ISSUE TITLE
asset versions in natscli make it impossible for scripts to download latest as the asset version is baked into the zip

### ISSUE THREAD

**Issue by aricart** [nats-io/natscli#341]
The following url path templates: `/<owner>/<name>/releases/latest/download/<asset-name>.zip` and `/<owner>/<name>/releases/download/<release>/<asset-name>.zip`. If you know the version number, then easy to inject the version for the asset name, but in the case of "latest", we cannot since the version is part of the asset.

**Comment by ripienaar** [comment]
It's easy enough to find what `latast` mean in terms of version though, there are countless little snippets on google for this.

Is it really worth putting more - many more - binaries out there to avoid that a quick curl/grep to the api?

**Comment by aricart** [comment]
we are also now going to store things in the edge, so we can identify latest,nightly
