### ISSUE TITLE
Not working -a and --all

### ISSUE THREAD

**Issue by dselans** [nats-io/natscli#345]
Trying to purge all streams via `nats stream purge -a` but am always greeted with an interactive prompt.

Am I missing something?

Same thing happens for `nats consumer rm -a`.

**Comment by ripienaar** [comment]
The all flag only really reflections selecting and listing streams. 

Without all you would not see certain streams - those holding kv, obj, mqtt state etc - with all you see tbem. 

We do not support pouring all streams in one go.  I will improve the help description

**Comment by dselans** [comment]
I just went with:

```

for i in `nats stream ls --json | jq '.[]' | sed s/\"//g`; do nats stream rm $i -f; done

```

Works for me!

Sent via Superhuman ( ***@***.*** )

**Comment by ripienaar** [comment]
Tried to make wording a bit clearer in https://github.com/nats-io/natscli/pull/348, also made the `-n` flag so you could again do `for i in $(nats s ls -n); do nats stream rm $i -f;done`

**Comment by dselans** [comment]
Awesome - thank you!
