### ISSUE TITLE
nats account info - return acc name

### ISSUE THREAD

**Issue by egodigitus** [nats-io/natscli#349]
Currently the `account info` command is not returning the name of the account.
This seems like a helpful feature for a multi-tenancy account setup.
The name of the current user would also be helpful without decoding the JWT.
Doesn't seem like the name is sensitive information at all.

**Comment by ripienaar** [comment]
Unfortunately the server does not make this available - though there was some talk about adding it maybe. Will keep it open in case the server ever get it. For now not much I can do.

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/644

Will support nats 2.10, shows user name, account name, permissions.
