### ISSUE TITLE
dial tcp timeout | JetStream system temporarily unavailable (10008)

### ISSUE THREAD

**Issue by Kaarel** [nats-io/natscli#353]
nats --version: 0.0.28

Today this happened when trying to use the nats cli tool:

`nats consumer report`
nats: error: setup failed: dial tcp 170.170.170.170:4222: i/o timeout
`nats consumer report`
nats: error: could not select Stream: JetStream system temporarily unavailable (10008)

The third attempt worked as expected. This took place within a time windows of a few seconds. I guess I got "lucky" to have hit this scenario as I haven't experienced this before nor after.

We've a 3 node cluster. We had `client_advertise: host.internal` in nats server config. `host.internal` resolves to 170.170.170.170 by our DNS. However that IP is not valid any more. The DNS hasn't been updated correctly.

Interesting that even though the nats cli tool knows that localhost:4222 is good to use, it for some reason decided to use an alternative. Presumably after initial handshake, otherwise how else would it know about that IP?

**Comment by ripienaar** [comment]
Yes it learns all the names via gossip - if you configure advertise names on tbe servers this will be avoided. 

Not much I can do here. It’s server config one part and another part the jetstream system was without a leader. Both areas outside of the CLI control.

**Comment by Kaarel** [comment]
I guess I'm trying to say that from my user's perspective the behaviour is unintuitive. I understand that underneath cli is using a nats client library that has auto server discovery and selection. But from my point of view I am executing a single command against a localhost which I know to be live. I gather that under the covers a single `consumer report` issues multiple requests to NATS. What's unintuitive is that all of those, it appears, could go to different servers.

**Comment by ripienaar** [comment]
No, they wont all go to different servers unless in the middle of this there is a disconnection - which would result in the entire thing failing with an error.

I think you're confusing 2 concurrent events.  The "temporary unavailable" error is the nats server not having a quorum and so replying with that error.  For you to get that means the request and reply connectivity worked, the discovery has nothing to do with this.
