### ISSUE TITLE
Get EOF error when running a nats command on MAC

### ISSUE THREAD

**Issue by mathiasvdb1998** [nats-io/natscli#372]
I installed the nats cli on my new macbook pro (M1). 
After installing and running for example `nats sub test`, I receive this error: `nats: error: EOF, try --help`
Can anyone please help me with this issue?

**Comment by ripienaar** [comment]
does it happen after some time? could be server closed the connection

**Comment by mathiasvdb1998** [comment]
No, it happens immediately and the server is running.

**Comment by ripienaar** [comment]
Any logs from the error?

**Comment by mathiasvdb1998** [comment]
<img width="427" alt="Screenshot 2022-03-04 at 16 43 22" src="https://user-images.githubusercontent.com/49117530/156794388-56ee1cb3-164e-4fc2-b995-5b848b2f5b52.png">

Not really

**Comment by ripienaar** [comment]
on the nats server, any logs?

**Comment by ripienaar** [comment]
If you can run the server  with -DVV

**Comment by mathiasvdb1998** [comment]
I can't telnet to the server.
![Screenshot 2022-03-04 at 19 51 03](https://user-images.githubusercontent.com/49117530/156824110-476768ab-ad16-47cc-95f4-e5e7e0b3b288.png)

I'm running the nats server in a Docker container. Maybe that causes the problem?

**Comment by ripienaar** [comment]
You probsbly need to expose the port or point it at the right port - regardless not a CLI issue then
