### ISSUE TITLE
Defect: nil pointer when editing a tag

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/natscli#375]
1) Create a stream without a tag

```
$ nats s create mystream
```
(answer questions)

2) Edit the stream with the --tags argument.

```
$ nats s edit mystream --tags foo
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x19e7719]

goroutine 1 [running]:
github.com/nats-io/natscli/cli.(*streamCmd).copyAndEditStream(0xc0000e0280, 0xc0001c1bb0, 0xd, 0x0, 0x0, 0xc0000e6180, 0x1, 0x4, 0x0, 0xffffffffffffffff, ...)
	/Users/colinsullivan/Dropbox/go/src/github.com/nats-io/natscli/cli/stream_command.go:1188 +0x1f9
github.com/nats-io/natscli/cli.(*streamCmd).editAction(0xc0000e0280, 0xc00015e000, 0x0, 0x0)
	/Users/colinsullivan/Dropbox/go/src/github.com/nats-io/natscli/cli/stream_command.go:1266 +0xa38
gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc0001b60d8, 0xc00015e000, 0x0, 0x0)
	/Users/colinsullivan/Dropbox/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/actions.go:28 +0x6d
gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc0000e4000, 0xc00015e000, 0x0, 0x0)
	/Users/colinsullivan/Dropbox/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:557 +0xdf
gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc0000e4000, 0xc00015e000, 0xc000149920, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc00019e700)
	/Users/colinsullivan/Dropbox/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:390 +0x95
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc0000e4000, 0xc00013c130, 0x5, 0x5, 0xc000509338, 0xc00019e700, 0x10, 0x20)
	/Users/colinsullivan/Dropbox/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:222 +0x228
main.main()
	/Users/colinsullivan/Dropbox/go/src/github.com/nats-io/natscli/nats/main.go:66 +0x1a10

**Comment by ripienaar** [comment]
Thanks. I wonder if tags should even be editable? It’s not like we will move a stream elsewhere if it now doesn’t match the server is on?

obviously shouldn’t npe though will fix.

**Comment by ColinSullivan1** [comment]
I agree, not thinking they should be today.  Although it would be a really cool feature if the server could move assets via tags.

This creates a few questions though:

1) What happens if an asset is moved and there are tags?  Does it get assigned all tags of the new server?
2) Should stream restore support tags? (I think so, might want to move it that way or restore it to a different server)
3) Should stream copy allow tags?  e.g. copy a stream from one region to another.

Probably more cases as well...

**Comment by ripienaar** [comment]
Yeah interesting. We recently turned down some changes as supported by restore cos it was just not working - like renames. 

I will fix the npe but we should discuss with Derek

**Comment by ripienaar** [comment]
> What happens if an asset is moved and there are tags? Does it get assigned all tags of the new server?

curious about your thinking here, like even on initial placement we dont give it the tags of the server, we treat the tags as a sub selection / venn diagram type thing.  But a server could have ten tags and a stream can have 1 and thats totally fine.

So I am wondering what the background is of that question though maybe I am missing something.

For copy we'd need to accept new tags for the new stream I guess

**Comment by ColinSullivan1** [comment]
No background, just a few thoughts at this point - you're not missing anything.

**Comment by ripienaar** [comment]
Removed storage, cluster and tags options from stream edit command and also fixed the underling cause for the npe
