### ISSUE TITLE
Support for skipping backoff policy by flags only

### ISSUE THREAD

**Issue by mugioka** [nats-io/natscli#376]
Hi,
Currently not supported to skip backoff policy in command line.
It would be nice to be able to skip the backoff policy with just a flag.

https://natsio.slack.com/archives/CM3T6T7JQ/p1646815941531729?thread_ts=1646810411.972319&cid=CM3T6T7JQ

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/377
