### ISSUE TITLE
misleading or wrong consumer info

### ISSUE THREAD

**Issue by sarathsp06** [nats-io/natscli#382]
## Overview
Consumer info as presented by nats-cli shows consumer and stream sequence. From my understanding stream sequence should be greater than or equal to the consumer sequence.  It is not documented as well. 

Is my expectation correct if not what is consumer sequence and stream sequence  

<img width="794" alt="image" src="https://user-images.githubusercontent.com/964542/158785653-daa056e0-033c-4535-a707-809f8ebcd0cd.png">

## Tasks

- [ ] Outline documentation approved
- [ ] Create an ADR if applicable 
- [ ] docs.nats.io updated
- [ ] Supporting blog posts or videos for marketing

**Comment by ripienaar** [comment]
That's an incorrect assumption. Stream Sequence is the pointer to the exact message, Consumer sequence though is a ever increasing counter for consumer actions. 

So for example a stream with 1 message in it would have stream sequence of 1, but if the consumer attempted 10 deliveries of that message consumer sequence would be 10 or 11.

These 2 numbers are not directly related.
