### ISSUE TITLE
nats: error: could not create Stream: nats: no servers available for connection

### ISSUE THREAD

**Issue by bobbybhaskar** [nats-io/natscli#386]
I'm trying to set up a storage for our `ORDERS` related messages. I'm getting error as showing below:
![image](https://user-images.githubusercontent.com/30714775/159267749-2a77a6ac-6921-4483-bd4e-bd3f7d7d8888.png)

**Comment by ripienaar** [comment]
it means there is no nats server on `localhost:4222` or whatever you configured in contexts.

pass `--server some.server:4222`

**Comment by bobbybhaskar** [comment]
Hi @ripienaar

can you share the link of  "jetstream service" installing in windows. I'm able to installed the nat server in windows, but I'm unable to find for jetstream service in windows 

Thanks,

Bobby

**Comment by ripienaar** [comment]
It is not a separate service. You configure nats server to offer jetstream. 

Please review https://docs.nats.io/nats-concepts/jetstream
