### ISSUE TITLE
Add an option to make a request and receive multiple replies

### ISSUE THREAD

**Issue by tbeets** [nats-io/natscli#403]
Currently both `nats req` and `nats pub --wait` exit after one reply received.  This prevents usage/demonstration of voting/multi-ping pattern of service request (multiple service responders receive the request and individually reply).

Propose adding a _reply wait duration_ option such that any inbox replies received up to the expiry of reply wait duration are printed by CLI.

**Comment by ripienaar** [comment]
The nats.go request function doesn’t have such an option. Would need to implement own request reply. 

Probably also suggests that it wouldn’t be an easy thing for users to duplicate in code.

**Comment by tbeets** [comment]
Easy to do "in two lines" but looking for a one-liner for demo.

```
nats sub myinbox
nats pub foo "hello" --reply=myinbox
```

**Comment by ColinSullivan1** [comment]
`Would need to implement own request reply.` - challenge accepted.  It's not super performant, muxing and such, but gets the job done.

**Comment by ColinSullivan1** [comment]
Thinking about it, could expand this with a count and the timer... e.g.  wdyt?https://gist.github.com/r4um/c1ab51b8757fc2d75d30320933cdbdf6
