### ISSUE TITLE
Dns name resolve from vpn

### ISSUE THREAD

**Issue by z0mb1ek** [nats-io/natscli#408]
I use cli installed from brew and use openvpn for my work environment, but I cannot connect to cluster:

`nats: error: setup failed: dial tcp: lookup nats.dev.svc.cluster.local on 192.168.88.1:53: no such host`

all other tools work great through vpn

**Comment by ripienaar** [comment]
I don’t think I do anything special dns wise. Just rely on the go standard library. 

But I suspect what’s happening is NATS is learning names of your cluster via its topology discovery and you do not configure advertise names that are correctly resolvable.

**Comment by z0mb1ek** [comment]
this name is resolving by ping command:

> ~ ❯ ping nats.dev.svc.cluster.local
PING nats.dev.svc.cluster.local (10.111.4.53): 56 data bytes
64 bytes from 10.111.4.53: icmp_seq=0 ttl=61 time=15.877 ms
64 bytes from 10.111.4.53: icmp_seq=1 ttl=61 time=20.659 ms
^C

moreover this dns successfully resolve when I use DataGrip for example for going to db in this cluster

**Comment by ripienaar** [comment]
Hard to say. For that I just call out to nats.go. 

@kozlovic or maybe @wallyqs might have seen something like this before?

**Comment by z0mb1ek** [comment]
see this https://github.com/golang/go/issues/12524 and in my config:
<img width="546" alt="Screenshot 2022-04-09 at 22 30 03" src="https://user-images.githubusercontent.com/1172005/162589001-59eee2a7-ecc3-4204-829a-6c18787cf15d.png">

**Comment by z0mb1ek** [comment]
no I have not, I gave you a screen of my config, it is alone

**Comment by ripienaar** [comment]
Sure, you wont see from that one file that you also have other files in `/etc/resolver/*`, you linked the issue which states a problem that specifically relates to those files, so seems like a reasonable question to ask.

Not sure, I guess you can do a test build locally without disabling CGO and seeing if it resolves the issue for you.

**Comment by wallyqs** [comment]
hi @z0mb1ek, checking just in case where you using auth credentials and/or a load balancer when you ran into this?

**Comment by krak3n** [comment]
I'm also hitting this issue trying to connect to out  nats cluster deployed in k8s over VPN (Cloudflare WARP).

We do have accounts and mTLS configured. If I use pure `nats.go` it works fine but through the CLI it fails:

```go
package main

import (
	"log"

	"github.com/nats-io/nats.go"
)

const NATS_URL = "nats://cluster.namespace.svc.cluster.local:4222"

func main() {
	opts := []nats.Option{
		nats.RootCAs("ca.crt"),
		nats.ClientCert("tls.crt", "tls.key"),
	}

	conn, err := nats.Connect(NATS_URL, opts...)
	if err != nil {
		log.Fatal(err)
	}

	js, err := conn.JetStream()
	if err != nil {
		log.Fatal(err)
	}

	for stream := range js.StreamNames() {
		log.Println(stream)
	}
}

// Outputs
2022/06/13 13:00:06 MY_STREAM_NAME
```

However this does not work with `natscli` (IP obfuscated):

```sh
nats --tlscert=./tls.crt --tlskey=./tls.key --tlsca=./ca.crt -s nats://cluster.namespace.svc.cluster.local:4222 stream ls
nats: error: setup failed: dial tcp: lookup cluster.namespace.svc.cluster.local on X.X.X.X:53: no such host
```

In my `/etc/resolver/cluster.local` (IP address obfuscated):

```
nameserver X.X.X.X
```

**Comment by ripienaar** [comment]
I think in the case of `/etc/resolver/cluster.local` files you could probably compile the CLI yourself with CGO enabled and that would resolve

**Comment by krak3n** [comment]
ahhh ok @ripienaar I installed via brew so will give a go at compiling locally 👍

**Comment by ripienaar** [comment]
Will close this, let us know if you still have issues.
