### ISSUE TITLE
`nats server info` is not working

### ISSUE THREAD

**Issue by 1995parham** [nats-io/natscli#436]
We set up our NATS cluster with Jetstream support on Kubernetes with helm chart, and we don't have any form of authentication. `natscli` works, but some commands like `nats server info` report the following error:

```
 ensure the account used has system privileges and appropriate permissions
```

But we don't have any form of authentication. For solving this, we need to explicitly define `$SYS` account in our configuration?

**Comment by ripienaar** [comment]
Yea, without a system account the information is not available.

**Comment by rodrigc** [comment]
@jnmoyne clarified the docs in https://github.com/nats-io/nats.docs/pull/493 
See: https://docs.nats.io/running-a-nats-service/configuration/clustering/jetstream_clustering#configuration
