### ISSUE TITLE
feat: daemon mode

### ISSUE THREAD

**Issue by drev74** [nats-io/natscli#456]
Hello

I'm new to NATS and natscli. I'm running a NATS JetStream with `nats server run --jetstream AJC`.
I eventually need to log out from my VM, where I run this. This makes me drop the server.

Is there a way to run a nats server in a daemon mode? Smth like `nats server run -d --jetstream AJC`, where you normally specify `-d` to run in a daemon mode. 

I'm not sure whether this is a documentation or a feature request.

**Comment by ripienaar** [comment]
For that you need to set up a nats-server instance perhaps in a container or kubernetes. The “nats server run” is specifically just for quick access to a local development environment that’s ephemeral. 

See docs.nats.io

**Comment by drev74** [comment]
Hi @ripienaar 
Thanks for your advice. I was following [this](https://docs.nats.io/running-a-nats-service/introduction/running) to run a `nats-server`.

However, there's still no option to run `nats` in a daemon mode. I wanna run it on a VM and purposely avoid Docker. How do I run `nats` on a bare metal in a daemon mode ?

**Comment by ripienaar** [comment]
Use the systemd units found here https://github.com/nats-io/nats-server/tree/main/util

**Comment by drev74** [comment]
I found an old discussion on this [here](https://github.com/nats-io/nats-server/issues/8)

**Comment by drev74** [comment]
@ripienaar thanks for your advice. `systemd` does the job
