### ISSUE TITLE
Ability to prevent interactive mode.

### ISSUE THREAD

**Issue by scottf** [nats-io/natscli#469]
It would be useful to be able to run the cli in non-interactive mode, so it can be run from a non-go program such as a Java client.

If there was a flag or an environment variable (or both) that could be set to tell the cli not to offer interactive mode and instead just error if it cannot process the command.

For instance `nats s info` will offer a list of streams. This mode would just error as if it does not know the stream, or some appropriate response.

**Comment by ripienaar** [comment]
We have some places where we already detected non interactive runs and reported a problem - but some major parts didnt have it.

Now as a first stab I added detection for a terminal or not in all the places that prompts, can you see if this fixes your problem? Should be better

**Comment by scottf** [comment]
Got the latest, tested `nats s info` and it returned an error instead of prompt. Looks good, thanks!
