### ISSUE TITLE
`nats kv put` hangs for empty (`""`) value

### ISSUE THREAD

**Issue by heikkilamarko** [nats-io/natscli#482]
`nats kv put` hangs for empty (`""`) value as shown in the screenshot below:

![Screenshot 2022-06-01 at 15 01 19](https://user-images.githubusercontent.com/3757314/171403206-83f89762-dd6c-4494-b6ed-d11aa82ba67a.png)

**Comment by ripienaar** [comment]
It’s waiting for input on stdin so you can pipe a file into it

**Comment by heikkilamarko** [comment]
Thanks for the quick reply.
