### ISSUE TITLE
Confusing default context

### ISSUE THREAD

**Issue by jonaslagoni** [nats-io/natscli#492]
When starting out you probably create a context, and sometimes that context is incorrectly created. 

My first reaction was to remove it and try again from scratch, but that leaves you with:

```
$ nats context rm nats
? Really delete context "nats" Yes
nats.exe: error: cannot remove the current active context, try --help
```

Then I thought there was a `default` one I could switch back to, basically the initial context when first launched. However, that is not possible as you cannot remove the active context.

The only solution I see is to create the new one first, and then remove the old one. Seems a bit like a bad user experience, especially if I want to keep the name of the context.

Alternatively I could edit the context, but I have not attached an editor to the cli yet, and have not reached that far into setting it up. That's why I do not consider it an alternative.

**Comment by ripienaar** [comment]
Yeah that’s an annoying situation sorry you had experience. 

So I still don’t like the idea of deleting the selected context but perhaps if we allowed that delete to happen if the selected one is the only context things would be fine?

**Comment by jonaslagoni** [comment]
> So I still don’t like the idea of deleting the selected context but perhaps if we allowed that delete to happen if the selected one is the only context things would be fine?

I understand that, that would also be a weird behavior 🤔

Yes, either that, or you always have a `default` one, meaning no context, that you can switch back to, then the requirement of always having a context would be fine. Since the initial state of the CLI is having no context, that should work in theory, right? 🤔

**Comment by ripienaar** [comment]
Yeah, I'd rather not have a concept of a default context - many people have no idea about contexts and don't care so it might cause weird interactions.

So I think safest is just to allow removing the selected context when it's the only context.

I'll look at that later this week, thank you

**Comment by ripienaar** [comment]
Next release allows deletion of the selected context if its the only context
