### ISSUE TITLE
Can't create a stream with sources non-interactively

### ISSUE THREAD

**Issue by mprimi** [nats-io/natscli#496]
Minor inconvenience that makes scripting `nats` hard when creating a stream that has sources.

Example: 
```
$nats stream add --source=stream-foo --source=stream-bar [...]
```

For each source, I am asked interactively 3 questions:

```
? Adjust source "stream-10" start
? Import "stream-10" from a different JetStream domain
? Import "stream-10" from a different account
```

As far as I can tell, there's currently no flag I can pass to bypass this interactive prompts. e.g.: `--same-account-sources --same-domain-sources --no-adjust-sources`.

**Workaround**
I tried to cheat and write a bunch of newlines into the process `stdin` (to simulate me hitting enter and accepting the default choice), but this doesn't work: `nats: error: Could not request source details: cannot ask for confirmation without a terminal`.

**Comment by ripienaar** [comment]
It would be a vast number of flags and noise and in help etc so I chose not to support that. 

However you can still do it with the CLI as —source takes a JSON string 

https://github.com/nats-io/jsm.go/blob/be84928cc782c1569ae2365c78e9577bf687c345/api/streams.go#L406

stick that into —source and you can configure any source related setting. Not the most friendly thing but I can’t realistically add all these flags for sources and mirrors both especially since you can add 100s of sources to a single stream the flag based approach would be impossible

**Comment by mprimi** [comment]
Agreed that flag-based approach to configure each source independently would be an unreasonable amount of work.
But to be clear, that's not what I was suggesting. 
I was suggesting a small set of flags (3) to communicate "apply default suggested in prompt, rather than prompting me".
For `stream add` with sources, that would be:
 - `--same-account-sources` 
 - `--same-domain-sources`
 - `--default-start-sources`

That seems *doable* by looking at the code. If I submit a PR for such a chance, would you accept it? It's ok to say no.

Thanks for the pointer to JSON input, I had no idea, and that solves my current (and possibly future) problems. Thank you!

**Comment by ripienaar** [comment]
Yeah I am not sure tbh, sources/mirrors is niche enough at the moment and the CLI is already a mine field of options (booleans are especially hard to deal with as each boolean has 3 values) that I am reluctant to add more options for such a niche feature.

However your suggestion is an interesting and solid approach, I just dont really want more options that shifts the behavior would rather stick to things that directly apply stream properties as options only.  

For sure I need to first get some features in to make booleans have fewer states (true, false, not given by user) as handling these are extremely awkward.

You also have to consider how this interact with stream edit for example
