### ISSUE TITLE
"--creds" flag is ignored when overriding the default context

### ISSUE THREAD

**Issue by goku321** [nats-io/natscli#503]
## Defect

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included nats.go version
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Versions of `nats.go` and the `nats-server` if one was involved:
`nats.go`: 0.0.28
`nats-server`: 2.8.4
#### OS/Container environment:
macOS Monterey
#### Steps or code to reproduce the issue:
1. Setup a nats context and select it as default
2. Execute a nats command and override the current context using `--creds` flag (for ex - `nats --creds user.creds account info`)
#### Expected result:
`nats` command should use the user creds provided using `--creds` flag instead of the default context
#### Actual result:
`nats` command ignores the `--creds` flag and uses the default context

**Comment by ripienaar** [comment]
I cannot reproduce this one, creds and all other settings do local overrides and if I add some debug printfs into the code I can see its active.

A silly way to test this is to add a incorrect credential path:

```
$ nats ctx add creds --creds /nonexisting1 --select --server localhost:4222
$ nats account info
nats: error: setup failed: nats: open /nonexisting1: no such file or directory
$ nats account info --creds /other
nats: error: setup failed: nats: open /other: no such file or directory
```

so from this I can tell the override is working, can you do a similar check for me?

**Comment by goku321** [comment]
Thanks @ripienaar . I can confirm that `--creds`  does overrides the local setting. Can you confirm If this override works with the `--user` flag as well?

![Screenshot 2022-06-21 at 2 49 41 PM](https://user-images.githubusercontent.com/12848015/174765003-20c1d4e8-520a-4dc8-bd2a-abec8c7db3ea.png)


In the above screenshot, `a2` does not exists while `a1` does (I did not set any default user while creating the context. Is this referring to an user created with `nsc`?)

Also, Is it possible to override the default context with `--server` and `--creds` flag? I tried but it didn't seem to work

**Comment by ripienaar** [comment]
all these flags override correctly.

**Comment by ripienaar** [comment]
```
$ nats account info --server n1-sfo|grep "Connected Server Name"
   Connected Server Name: n1-sfo
$ nats account info |grep "Connected Server Name"
   Connected Server Name: n1-lon
```

server overrides correct also
