### ISSUE TITLE
can't edit stream to remove rollups

### ISSUE THREAD

**Issue by kino71** [nats-io/natscli#513]
On a stream ("foo") that has:
       Allows Rollups: true

nats-cli doesn't allow to change to false:

nats str edit foo --no-allow-rollup
No difference in configuration

thanks

**Comment by kino71** [comment]
I have just found that it works if rollup is changed through json config:

nats str edit [stream] --config [config.json]

**Comment by ripienaar** [comment]
Yeah, the basic editing ability works - the bug is about detecting one of the 3 states of boolean - supplied, true or false.  Will fix, some recent changes to the cli library makes it at least possible

**Comment by ripienaar** [comment]
Actually I fixed this already when I moved to the new CLI libary, but not released yet:

```
$ nats s edit X --no-allow-rollup
Differences (-old +new):
  api.StreamConfig{
        ... // 21 identical fields
        DenyDelete:    false,
        DenyPurge:     false,
-       RollupAllowed: true,
+       RollupAllowed: false,
        AllowDirect:   false,
  }
? Really edit Stream X Yes
```
