### ISSUE TITLE
Cannot create ephemeral consumer subscription to a mirrored stream

### ISSUE THREAD

**Issue by chris13524** [nats-io/natscli#517]
When mirroring a Stream between two JetStream instances, it is not possible to utilize the `nats sub` command to subscribe to the downstream stream by creating an ephemeral consumer. This is because the CLI only uses the passed subject to look up the stream, however mirrored streams do not have subjects, only in the source stream.

The JetStream Go API [supports subscribing to a specific stream](https://github.com/nats-io/nats.go/blob/main/js.go#L1438). I think support for this could be added pretty easily in this switch statement: https://github.com/nats-io/natscli/blob/main/cli/sub_command.go#L247

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/520
