### ISSUE TITLE
Docker image for JetStream management & init containers

### ISSUE THREAD

**Issue by steevehook** [nats-io/natscli#532]
## Suggestion

Add Docker image to be able to invoke the `nats` binary directly by running a container without installing it on the host or using the client API for JetStream Management. I personally think it would be really useful especially when running init-containers that create the desired state before the application can start or before the tests can be run

P.S. If that's an option, would love to contribute to such a wonderful project

**Comment by ripienaar** [comment]
See the synadia/nats-box container

**Comment by steevehook** [comment]
Found the official version from nats-io, here's an open PR if anyone can have a look

https://github.com/nats-io/nats-box/pull/35
