### ISSUE TITLE
Command can get stuck in infinite reconnect loop

### ISSUE THREAD

**Issue by mprimi** [nats-io/natscli#534]
I have observed the following a few times:

```
$nats -s <...> --creds <...> stream cluster step-down <STREAM>

12:40:48 Requesting leader step down of "<CLUSTER>" in a 3 peer RAFT group
12:43:32 Disconnected due to: EOF, will attempt reconnect
12:43:32 Reconnected [nats://<S1>:4222]
12:43:55 Disconnected due to: EOF, will attempt reconnect
12:43:55 Reconnected [nats://<S2>:4222]
12:44:40 Disconnected due to: EOF, will attempt reconnect
(...)
16:00:41 Disconnected due to: EOF, will attempt reconnect
16:00:45 Reconnected [nats://<S2>:4222]
16:05:19 Disconnected due to: EOF, will attempt reconnect
16:05:21 Reconnected [nats://1<S2>:4222]
16:07:07 Disconnected due to: EOF, will attempt reconnect
16:07:07 Reconnected [nats://<S1>:4222]
```

As you can see from timestamp, this has been stuck for 3+ hours. It never seem to recover.

Meanwhile, the rest of the cluster is operational: clients are able to make progress. 
Therefore I think this may be just `natscli` getting stuck in a corner case.

If it's any help: this happens in a cluster where I am injecting failures. There are 'chaos monkeys' restarting servers every few minutes. This particular process that got stuck, is a chaos monkey forcing streams leadership changes.
The cluster is made up of 5 nodes: 2 "front" connection nodes (no JS) and 3 backend JS nodes (nobody connects directly to them).

**Comment by ripienaar** [comment]
Hard to say, most of the code around there should timeout after a few tries, however I do configure the client with infinite reconnects so at least that part is not a surprise.

Eyeballing the code I cant spot the point of being stuck, however I did fix a timer that should have been a ticker.  Anyway seems like a edge case so will close this hoping that ticker change will resolve it.

Thanks for the report
