### ISSUE TITLE
Account backup not creating backup of all streams in account

### ISSUE THREAD

**Issue by sourabhaggrawal** [nats-io/natscli#541]
## Defect
When creating  backup of an account using ./nats account backup, it is not creating backup up all streams & consumers of that account. 
I have 416 stream and 80,000 consumers in one account and backup command is only creating creating backup of 256 streams and 36,850 consumers. Screenshot attached for reference.
Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `nats-server -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (https://stackoverflow.com/help/mcve)

#### Expected result:
All streams and consumers backup should have been created.

#### Actual result:
Only half of the streams and consumers backup

<img width="803" alt="Screenshot 2022-07-18 at 1 30 14 PM" src="https://user-images.githubusercontent.com/70515711/180702982-9b13f84e-01ae-403f-b4f5-be29141b058b.png">
 
<img width="707" alt="Screenshot 2022-07-18 at 1 30 32 PM" src="https://user-images.githubusercontent.com/70515711/180703801-0c9abeb5-7db9-408e-a24a-b7f0024c300c.png">

**Comment by ripienaar** [comment]
Will review. We had another report of some operations not acting on all streams but not been able to reproduce. Will check again. 

Will review later this week or early next as I am out. Thank you.

**Comment by ripienaar** [comment]
Can you confirm that nats s ls -a —names also returns only a subset?

And if so can you run that with —trace and show me the first part of the STREAMS api call result? There should be some things about offset and total

**Comment by kozlovic** [comment]
@ripienaar I believe that this is fixed now in main with https://github.com/nats-io/nats-server/pull/3287. Should be in the nightly tonight (7/25/2022)

**Comment by ripienaar** [comment]
Yup, fixed, thank you
