### ISSUE TITLE
subscribe --count is ignored when using --raw or --dump

### ISSUE THREAD

**Issue by oren-nonamesecurity** [nats-io/natscli#543]
`nats subscribe --count 3 topicname` will print 3 messages and then exit.
But `nats subscribe -r --count 3 topicname` runs forever. 
And same for `nats subscribe --dump=output/ --count 3 topicname`

**Comment by ripienaar** [comment]
I think this is already fixed in https://github.com/nats-io/natscli/pull/495 and will be in the next release.

Thank you for the report

**Comment by oren-nonamesecurity** [comment]
Thanks!

Is there a planned date for next release?

**Comment by ripienaar** [comment]
Will release after the next sever release, thats already a bit late so will be soon.
