### ISSUE TITLE
Stream rm with --force should not require online leader

### ISSUE THREAD

**Issue by tbeets** [nats-io/natscli#544]
There are scenarios where a stream may not  have active peers and the operator needs to remove the now-defunct stream placement from the meta layer.  This management action is allowed by the server in a direct `$JS.API` publish by System account, but cannot be performed with the NATS CLI (v0.33).

If `nats stream rm --force [stream name]` is called, NATS CLI should not require a successful pre-call to `info` before issuing a remove API call to the stream API.

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/554/commits/cdc79521b751246b962694496b143ae87eb3943c
