### ISSUE TITLE
Nats Reply - Data Payload Feature Request

### ISSUE THREAD

**Issue by jordan-rash** [nats-io/natscli#578]
Would love to be able to manipulate the data payload in the CLI for a request/reply, much like we already can with the subjects and template functions.

For example, given the following request
```
nats req NAME '{"name":"Jordan"}'
```

Would want to rely with 
```
nats reply NAME "Hello, {{ Data.name }}" //output: Hello, Jordan
```

**Comment by ripienaar** [comment]
I definitely could not dig into the actual content sent, but i can expose the content verbatim.  Would that still be worth doing for you?

Nats is payload agnostic in concept, so while most of us send JSON you can send any data in any encoding format and I wouldnt want to give JSON prominence in the CLI

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/585

**Comment by jordan-rash** [comment]
Thanks!
