### ISSUE TITLE
Option to purge entire bucket 

### ISSUE THREAD

**Issue by kino71** [nats-io/natscli#580]
It is possible to purge a single key :
nats kv purge <bucket> <key> 
but not the entire bucket.

It would be nice to have <key> optional, to wipe the whole bucket if needed.

Fair to say that it is possible to purge the KV as stream:

nats s purge KV_[bucket]

thanks

**Comment by ripienaar** [comment]
So it's a bit more complicated I think, not sure making bucket purge work as we thought is right.

First conceptually the history is a audit trail and used to communicate to watchers, so key purge will delete all the entries and then put a purge entry into that key via rollup.  So it doesnt purge the data is removes history and tells watchers and those interested in audit that this was done.

If we bucket purge, to be within the general theme of things, we should do this whole purge dance per key, you wont get a bucket without data you'll get one where every key was purged.

You can then do `kv compact` to get rid of those purge markers, 

Essentially:

```
$ nats kv ls BUCKET | xargs -n1 nats kv purge --force X
$ nats kv history X y
╭───────────────────────────────────────────────────────────────╮
│                       History for X > y                       │
├─────┬──────────┬───────┬─────────────────────┬────────┬───────┤
│ Key │ Revision │ Op    │ Created             │ Length │ Value │
├─────┼──────────┼───────┼─────────────────────┼────────┼───────┤
│ y   │ 2        │ PURGE │ 23 Sep 22 10:11 UTC │ 0      │       │
╰─────┴──────────┴───────┴─────────────────────┴────────┴───────╯
```

And even tht wont work cos compact isnt PURGE aware

**Comment by ripienaar** [comment]
Ok I think `compact` is purge aware I missed something - anyway, just out right drop all the data isnt sometehing that sits well within the model or watchers etc today.

**Comment by ripienaar** [comment]
I'll keep it open while I think about it, likely for a few weeks :)

**Comment by ripienaar** [comment]
I'll close it, I think its just a bad idea.
