### ISSUE TITLE
Duplicate consumers

### ISSUE THREAD

**Issue by kumar18tushar** [nats-io/natscli#589]
Hi, 
I launched 10K individual clients, each launching 1 ephemeral subscriber (go routines),
Now when I do `nats consumer list -s <url>` on the stream, it returns me 64K consumers, with many of the consumers being duplicated. Something like this:

zyj4WHFj
zyj4WHFj
zyj4WHFj
zyj4WHFj
zyj4WHFj
zyj4WHFj
zyj4WHFj
zyj4WHFj
zza2KMqB
zza2KMqB
zza2KMqB
zza2KMqB

Specifications:
3 nodes nats cluster
R1 stream

PS: Was not creating any new consumers, rather just was listening on the already created ones, when I ran the nats consumer list command.

Can we please check?

**Comment by ripienaar** [comment]
As requested on slack please show the output with `--trace`

**Comment by kumar18tushar** [comment]
@ripienaar Given that the number of subjects and the number of consumers are huge, hence unable to capture the entire trace log.  This scenario can be easily reciprocated. I m facing almost all the time. `nats v2.9.0`
Few of the log lines that I have:
```
00:15:56 >>> $JS.API.CONSUMER.NAMES.<STREAM_NAME>
{"offset":0}

00:15:56 <<< $JS.API.CONSUMER.NAMES.<STREAM_NAME>
{"type":"io.nats.jetstream.api.v1.consumer_names_response","total":43,"offset":0,"limit":1024,"consumers":["1VFMyof4","2ZdzLS3E","5ozDj3fG","6SpKai9o","8oKKTYTW","9LjbjJs5","AFFjvX3z","Dio26Sp4","DqO82Ndh","HAe4sqZy","HIfiKWzL","Js6c7Knr","PPAa2mil","Q0WiThcj","SgF8BT8v","TeSD0twh","UUK67wvu","UX8zao24","XB5unfYe","XK28U9xw","XZT84ORh","ZGcSLvaQ","Zjm5ERwl","aPxbJuGF","bEQ70308","eS8VxU9l","fKRyPMfN","jSwf90s4","kTpWhupw","lIuZhA5p","lP9hPdkt","mQ0irHMn","nRzRVYaD","o5t2JYq8","pFT3gdEa","qzSLgSM4","randomname","s7rF31r0","t17GmIXy","u7errJ2q","uIYoduMf","vfa7EAYZ","whqP0TS4"]}

      46

**Comment by ripienaar** [comment]
What I want to see is if the duplicates are in one json message - it would make a few api calls paging through all the results. 

So there is one of two scenarios - the paging is broken and like the same consumer is in 3 pages. Or it’s worse than that and 1 page lists the consumer a few times.

**Comment by ripienaar** [comment]
Or maybe CLI is just interpreting wrong :) so need to see the data

**Comment by ripienaar** [comment]
The list you showed me have no duplicates? Sorry, cant help you with the information you provide.

**Comment by kumar18tushar** [comment]
Will try to provide you the complete trace..with smaller chunk of data.

**Comment by ripienaar** [comment]
Was able to reproduce, we'll fix it @kumar18tushar

**Comment by ripienaar** [comment]
It will be next server release not CLI so just keep an eye there. I will close here as it’s not the command line related
