### ISSUE TITLE
Progress bar on nats object put|get work inverted

### ISSUE THREAD

**Issue by rickardgranberg** [nats-io/natscli#593]
Was doing some testing of the Object Store feature and didn't understand why I didn't see the progress bars.

I ran: `nats object put <bucket> <file>` and `nats object put --progress <bucket> <file>` expecting to see a progress bar but did not. And yes, my file was over 20480 bytes.

To my surprise, running `nats object put --no-progress <bucket> <file>` makes the progress bar appear!

I've traced it to the lines https://github.com/nats-io/natscli/blob/1057211892d576f6b46c8c3a4861abb457e5668f/cli/object_command.go#L85 https://github.com/nats-io/natscli/blob/1057211892d576f6b46c8c3a4861abb457e5668f/cli/object_command.go#L97

The flag is named `--progress` with a default of `true` but the variable it's assigned to is named `noProgress` and it's used in that capacity on line https://github.com/nats-io/natscli/blob/1057211892d576f6b46c8c3a4861abb457e5668f/cli/object_command.go#L486 and https://github.com/nats-io/natscli/blob/1057211892d576f6b46c8c3a4861abb457e5668f/cli/object_command.go#L562

I'll be happy to provide a PR with a fix, but I'm a little uncertain if the intention was to have progress enabled or disabled by default.

**Comment by ripienaar** [comment]
hmmm, yeah i think logic is just reversed, should be always on

**Comment by rickardgranberg** [comment]
Alright. I'll work on a fix
