### ISSUE TITLE
Stream view should be more clear about the time delta

### ISSUE THREAD

**Issue by NickLarsenNZ** [nats-io/natscli#598]
I was trying to view a stream from a unix timestamp and wasn't sure why I was receiving:

```
nats stream view --since=1664807544 --subject=my.subject MyStream
nats: error: invalid duration
```

When I run `nats stream view --help` it just says:

```
  --since=SINCE      Start at a time delta
```

It finally dawned on me that I need to do it like this:

```
nats stream view --since=24h --subject=my.subject MyStream
```

I think the help text should be updated to give an example. Or `stream view` should support unix timestamps too.

**Comment by ripienaar** [comment]
I've clarified the help text a bit in https://github.com/nats-io/natscli/pull/603
