### ISSUE TITLE
Stream view should allow unlimited paging

### ISSUE THREAD

**Issue by NickLarsenNZ** [nats-io/natscli#599]
I'd like to be able to dump all messages in a stream without skipping pages.

The help text suggests I can specify a page size:

```
usage: nats stream view [<flags>] [<stream>] [<size>]

...

Args:
  [<stream>]  Stream name
  [<size>]    Page size
```

But when I specify either of these, I get some default paging size (seems to be `25`):

```
nats stream view --since=1664807544 --subject=my.subject MyStream 0
nats stream view --since=1664807544 --subject=my.subject MyStream 10000
```

It would be nice to be able to disable paging.

**Comment by ripienaar** [comment]
You could try “nats sub —stream X” it’s more orientated to just forever getting data. View is inherently paged and for interactive use. 

Sub can dump to files and more
