### ISSUE TITLE
server passwd output is misaligned

### ISSUE THREAD

**Issue by variadico** [nats-io/natscli#63]
```
$ nats server passwd
? Enter password [? for help] **********************
                              ? Reenter password [? for help] **********************

$2a$11$DAFPlebnj555dIvBLDk9D.Zi48QcXbdRd8JhsfpApgG4Hn9FO4cjC
```

This is what I use using Bash 5.1.4 and Gnome Terminal 3.38.2.

**Comment by ripienaar** [comment]
Hmm. Not much I can do to fix that it’s all the survey package. Hmm. Maybe I will put a Println() between on other terminals it would be a extra blank. 

Can you try running “reset” and see if it still does it?

**Comment by variadico** [comment]
Okay, just tried running `reset` before `nats server passwd`, but the result is the same.

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/64

**Comment by variadico** [comment]
```
$ nats server passwd
? Enter password [? for help] **************************************
? Reenter password [? for help] **************************************

$2a$11$qP8.dpLZRLH8uzlnTdmXlOi.2p26byo.RZSv/1CRO7MUMYr7lpHlW
```

Nice, works for me! 🎉
