### ISSUE TITLE
Path not supported for websockets

### ISSUE THREAD

**Issue by everactivetim** [nats-io/natscli#639]
It would appear that a path on a websocket server URL is not supported. The NATS library itself supports a ProxyPath option but the cli does not expose that or accept path as part of the server URL.

It's easy enough to check if the server URL has a path and construct the connection using the ProxyPath option but my question is: is that desirable or should the cli just expose a `--proxy-path` or some sort to use the ProxyPath option for connections? I have the former working but can submit a PR for either. Thanks!

**Comment by ripienaar** [comment]
Why would we not just interpret the url, say you say `--server ws://example.net/some/path` wouldnt that imply `ProxyPath("/some/path")` ? Seems better than adding a whole new option for this

**Comment by everactivetim** [comment]
@ripienaar - would you mind referencing the PR that fixed this? Thanks!

**Comment by ripienaar** [comment]
I dont have a PR that implemented it, I asked a question and had no response for 4 months so closed it.

**Comment by everactivetim** [comment]
But, AFAIK, it's not completed.

**Comment by ripienaar** [comment]
I don’t know or use websockets. So I ask clarifying questions towards a solution. If the one filing the issue doesn’t engage and we had no one else asking then it’s probably not important. 

I am not going to keep issues open for 1/2 of a year. 

You are welcome to reopen and engage in the discussion towards a solution.

**Comment by everactivetim** [comment]
OK, that's fine. My issue was more around the status of "Completed". Is there another status? If someone found this in the future it should be clear that it is not actually implemented and instead the issue was closed as "something other than completed".

**Comment by ripienaar** [comment]
GitHub does that automatically. I didn’t choose it.

**Comment by everactivetim** [comment]
![image](https://user-images.githubusercontent.com/38664824/229193972-17f7a446-13ab-4ac2-b281-a6f44bf1206f.png)

**Comment by kuklyy** [comment]
Hey @ripienaar. I prepared a PR in the JSM repo (https://github.com/nats-io/jsm.go/pull/487). Please take a look. Adding this to the upstream will be a huge quality-of-life upgrade for me.

**Comment by ripienaar** [comment]
Thanks, missed it there my appologies.  I left a comment there.

**Comment by ripienaar** [comment]
This is in main now if you want to give it a go :) Probably have to wait for next majorish release though
