### ISSUE TITLE
add documentation about the configuration file

### ISSUE THREAD

**Issue by remyleone** [nats-io/natscli#646]
It could be very useful to understand how to fill up this configuration file. what is the expected format and when there is an error how to debug it. Are the string expected the direct content of the user_jwt for instance or is it a path towards a file that contain a credentials file? For instance here: https://github.com/nats-io/nats.py#nkeys-and-jwt-user-credentials it is a path and not the direct content. 

```
{
  "description": "NATS Demo",
  "url": "",
  "token": "",
  "user": "",
  "password": "",
  "creds": "",
  "nkey": "",
  "cert": "",
  "key": "",
  "ca": "",
  "nsc": "",
  "jetstream_domain": "",
  "jetstream_api_prefix": "",
  "jetstream_event_prefix": "",
  "inbox_prefix": "",
  "user_jwt": ""
}
```

**Comment by ripienaar** [comment]
Generally they correspond to flags on the CLI and take the same thing, though `user_jwt` is not supported by the nats cli. And now that I look it's entirely unused and would have no effect.

Agree though, would be good to have docs for this.

**Comment by ripienaar** [comment]
Whats the matching setting in go you use for this? `UserJWTAndSeed` is probably the only one that make sense - and we dont have a seed option either here.  So please expand a bit about what you want to achieve

**Comment by remyleone** [comment]
I want to create some helper function (for instance package in our scaleway-cli) to:
- create credentials from our managed nats service 
- install it in the configuration file of a customer. 

I've created https://github.com/nats-io/natscli/pull/647 to improve the documentation on the README.

**Comment by ripienaar** [comment]
Ok but again please tell me what setting you want set in nats.go. All the context does is map json to nats.go options and today there is no option for user jwt.

**Comment by ripienaar** [comment]
Correct. We do want to add a few options to facilitate more flexibility - and also pluggable auth to the server that is being done now - at that point this will expand. 

For now really you just need a creds file looks like and user_jwt is unused

**Comment by ripienaar** [comment]
next version will show a detailed documented file on edit
