### ISSUE TITLE
Account Backup consumers flag is of type UnNegatableBoolVar

### ISSUE THREAD

**Issue by anthonyjacques20** [nats-io/natscli#666]
From the descriptions of `nats account backup`, it says the flag `--consumers` is `Enable or disable consumer backups` but in the code, the `consumers` flag is marked as `UnNegatableBoolVar` which means there is no `--no-consumers` option when from the description it seems like that should exist.

**Comment by ripienaar** [comment]
That means it’s disabled by default. To enable it pass —consumers.

**Comment by ripienaar** [comment]
Ah I see, it’s in fact true by default so yes it needs the —no support sorry about that will fix

**Comment by anthonyjacques20** [comment]
No worries! Yeah making it `false` by default would also fix it. Thanks for the quick response and looking into it!

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/667 Thank you
