### ISSUE TITLE
Show global options for subcommands

### ISSUE THREAD

**Issue by bruth** [nats-io/natscli#691]
A user was trying out `nats bench` and was not aware of the global options only reported by `nats -h`.

**Comment by ripienaar** [comment]
We used to. Then they didn’t see the options for a command cos too many options :)

might add some wording below saying see nats -h for global options?

**Comment by bruth** [comment]
Hm, `nsc` shows the global options.. grant it I know `nats` has way more options depending on the command, but personally I feel like it is easy enough to pipe to a pager or scroll in a terminal that information overload should be manageable as suppose to having them call a separate command :man_shrugging: But at a minimum the note for `Seeing nats -h` would be an improvement.

**Comment by ripienaar** [comment]
Specifically passing `--help` now shows them, contextual generated help does not to keep things readable but it does inform that globals can be shown with `--help`
