### ISSUE TITLE
JSON configuration generated cannot be consumed

### ISSUE THREAD

**Issue by kaskaz** [nats-io/natscli#692]
When adding a Pull Consumer to a given stream through NATS CLI, I end up by exporting the JSON configuration running `nats consumer info --json` for convenience of later configurations.
When consuming that configuration, using the same CLI version, I get the following error:

> nats: error: Consumer creation failed: consumer in pull mode requires explicit ack policy (0)

The command I execute is `nats consumer add --config=/configs/some_config.json` and I'm prompted to select the stream.

The following is the consumer configuration process:

> docker-desktop:~# nats consumer add SOME-STREAM-NAME SOME-SUBJECT-NAME
> ? Delivery target (empty for Pull Consumers) SOME-SUBJECT-NAME.SOME-STREAM-NAME
> ? Delivery Queue Group
> ? Start policy (all, new, last, subject, 1h, msg sequence) all
> ? Acknowledgement policy  [Use arrows to move, type to filter, ? for more help]
> ? Acknowledgement policy explicit
> ? Replay policy instant
> ? Maximum Allowed Deliveries -1
> ? Maximum Acknowledgements Pending 1
> ? Idle Heartbeat 30s
> ? Enable Flow Control, ie --flow-control Yes
> ? Deliver headers only without bodies No
> ? Add a Retry Backoff Policy Yes
> ? Backoff policy linear
> ? Minimum retry time 5s
> ? Maximum retry time 10s
> ? Number of steps to generate in the policy 5
> Information for Consumer SOME-STREAM-NAME > SOME-SUBJECT-NAME created 2023-02-05T23:19:49Z
> 
> Configuration:
> 
>         Durable Name: SOME-SUBJECT-NAME
>     Delivery Subject: SOME-SUBJECT-NAME.SOME-STREAM-NAME
>       Deliver Policy: All
>           Ack Policy: Explicit
>             Ack Wait: 30s
>        Replay Policy: Instant
>   Maximum Deliveries: 6
>      Max Ack Pending: 1
>       Idle Heartbeat: 30.00s
>         Flow Control: true
> 
> State:
> 
>    Last Delivered Message: Consumer sequence: 0 Stream sequence: 0
>      Acknowledgment floor: Consumer sequence: 0 Stream sequence: 0
>          Outstanding Acks: 0 out of maximum 1
>      Redelivered Messages: 0
>      Unprocessed Messages: 0
>           Active Interest: No interest

The generated configuration is the following:

```
{
  "stream_name": "SOME-STREAM-NAME",
  "name": "SOME-SUBJECT-NAME",
  "config": {
    "ack_policy": "explicit",
    "ack_wait": 30000000000,
    "deliver_policy": "all",
    "deliver_subject": "SOME-SUBJECT-NAME.SOME-STREAM-NAME",
    "durable_name": "SOME-SUBJECT-NAME",
    "flow_control": true,
    "idle_heartbeat": 30000000000,
    "max_ack_pending": 1,
    "max_deliver": 6,
    "replay_policy": "instant",
    "num_replicas": 0
  },
  "created": "2023-02-05T23:19:49.984678331Z",
  "delivered": {
    "consumer_seq": 0,
    "stream_seq": 0
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 0
  },
  "num_ack_pending": 0,
  "num_redelivered": 0,
  "num_waiting": 0,
  "num_pending": 0,
  "cluster": {
    "leader": "NBYPYKCAVIO2RVGDPAF34ECT5DGYPHJMH3YPKEEI6LIKUPD37G2WOZKU"
  }
}
```

Anyone getting the same behaviour?
Am I doing anything wrong?

**Comment by ripienaar** [comment]
for me, with your config, it works.  What version `nats` and server?

**Comment by kaskaz** [comment]
> for me, with your config, it works. What version `nats` and server?

nats-server v2.2.4
nats v0.0.35 (on nats-box v0.13.4)

**Comment by ripienaar** [comment]
You should use a much newer nats server

**Comment by kaskaz** [comment]
I just upgraded to the latest version and the configuration is successfully read.
However the consumer is not created despite of the output saying that it was created.

> nats consumer add SOME-STREAM-NAME SOME-SUBJECT-NAME --config /configs/some_config.json
> Information for Consumer SOME-STREAM-NAME > SOME-SUBJECT-NAME created 2023-02-08T16:32:56Z
> Configuration:
> 
> Name: SOME-SUBJECT-NAME
> Pull Mode: true
> Deliver Policy: All
> Ack Policy: None
> Replay Policy: Instant
> Max Waiting Pulls: 512
> Inactive Threshold: 5.00s
> 
> State:
> 
>    Last Delivered Message: Consumer sequence: 1 Stream sequence: 1
>      Unprocessed Messages: 452
>             Waiting Pulls: 0 of maximum 512

(Some messages were already written to the stream)

**Comment by ripienaar** [comment]
If it shows that then it was created. What is shown is the server confirming. 

How do you know it wasn’t created?

**Comment by kaskaz** [comment]
By running _nats consumer info (or report)_ the consumer is not listed there.

**Comment by ripienaar** [comment]
Well you configure it with a 5s inactive window. Did you use it within 5s?

**Comment by kaskaz** [comment]
I made the test again because I wasn't sure about it, but I still get the same result after running the report command.

**Comment by ripienaar** [comment]
This looks to me like some kind of weird defaults interaction like maybe the inactive timeout is some default being applied. Will investigate further. 

It is created just using a bad value for inactive timeout

**Comment by ripienaar** [comment]
I will check what is going on - but if you did the whole thing again meaning create by hand then grab the json and then create with —config it should now work. 

The problem here is something a config json from a old server against the new server (or new CLI) and I will look into that

**Comment by kaskaz** [comment]
Generating the consumer re-add it with the same cli/server version is not working.
Does the stream configuration/state has anything to do it with the consumer?

**Comment by ripienaar** [comment]
It shouldn’t. Show me your current json config please and I will try repro later this week

**Comment by ripienaar** [comment]
Also show stream config json

**Comment by kaskaz** [comment]
@ripienaar sorry for the delayed answer.
I followed your idea of creating streams and consumers in a new server, extract JSON config and use them.

So I'm using now _nats:2.9.14-alpine_ image and _nats-box v0.13.4_.
By creating a stream and consumer from CLI prompt and request JSON config, I can re-create the stream but not the consumer.
I leave you the configurations bellow, hope it helps!

### Stream

```
{
  "config": {
    "name": "STREAM-NAME",
    "subjects": [
      "STREAM-NAME.*"
    ],
    "retention": "limits",
    "max_consumers": -1,
    "max_msgs_per_subject": -1,
    "max_msgs": -1,
    "max_bytes": -1,
    "max_age": 0,
    "max_msg_size": -1,
    "storage": "file",
    "discard": "old",
    "num_replicas": 1,
    "duplicate_window": 120000000000,
    "sealed": false,
    "deny_delete": false,
    "deny_purge": false,
    "allow_rollup_hdrs": false,
    "allow_direct": false,
    "mirror_direct": false
  },
  "created": "2023-02-16T18:28:20.455777209Z",
  "state": {
    "messages": 0,
    "bytes": 0,
    "first_seq": 0,
    "first_ts": "0001-01-01T00:00:00Z",
    "last_seq": 0,
    "last_ts": "0001-01-01T00:00:00Z",
    "consumer_count": 0
  }
}
```

### Consumer

```
{
  "stream_name": "STREAM-NAME",
  "name": "CONSUMER-NAME",
  "config": {
    "ack_policy": "explicit",
    "ack_wait": 1000000000,
    "deliver_policy": "all",
    "deliver_subject": "CONSUMER-NAME.STREAM-NAME",
    "durable_name": "CONSUMER-NAME",
    "flow_control": true,
    "idle_heartbeat": 30000000000,
    "max_ack_pending": 1,
    "max_deliver": 5,
    "backoff": [
      1000000000,
      2000000000,
      3000000000,
      4000000000
    ],
    "replay_policy": "instant",
    "num_replicas": 0
  },
  "created": "2023-02-16T18:35:31.961705134Z",
  "delivered": {
    "consumer_seq": 0,
    "stream_seq": 0
  },
  "ack_floor": {
    "consumer_seq": 0,
    "stream_seq": 0
  },
  "num_ack_pending": 0,
  "num_redelivered": 0,
  "num_waiting": 0,
  "num_pending": 0
}
```

Btw, I'm assuming 2 things:
1. Using uppercase names doesn't make any difference.
2. I can replicate similar streams/consumers by changing only the names and subjects.

**Comment by tkeller-moxe** [comment]
Ran into this as well. 
Seems like just using the contents of the config solves it. 
EG from your config. Not ideal as it doesn't auto select the stream however. Better then nothing however. 
```
{
    "ack_policy": "explicit",
    "ack_wait": 1000000000,
    "deliver_policy": "all",
    "deliver_subject": "CONSUMER-NAME.STREAM-NAME",
    "durable_name": "CONSUMER-NAME",
    "flow_control": true,
    "idle_heartbeat": 30000000000,
    "max_ack_pending": 1,
    "max_deliver": 5,
    "backoff": [
      1000000000,
      2000000000,
      3000000000,
      4000000000
    ],
    "replay_policy": "instant",
    "num_replicas": 0
}
```

**Comment by ripienaar** [comment]
this is fixed in main for the `jq .config` case, so next release should sort you out @tkeller-moxe

**Comment by kaskaz** [comment]
Can you explain what `| jq .config` does?

So it's expected to create new consumers using just the `config` section or can we use more sections, like `stream_name` and `name`?

**Comment by ripienaar** [comment]
`jq .config` extracts just the `"config"` key from the json.

In next release this will not be needed.
