### ISSUE TITLE
Restore not honoring original stream's replica

### ISSUE THREAD

**Issue by kino71** [nats-io/natscli#693]
Apparently stream restore is not honoring stream's replica.
I did a stream backup from a cluster and restored into another, original stream was R3, destination stream was created R1 by natscli.

nats-cli 0.0.35

**Comment by ripienaar** [comment]
I can't seem to replicate this, can you show me `backup/backup.json` of your backup?

**Comment by kino71** [comment]
I apologize, I was really convinced that original stream was R3, it turned out to be R1.
I'm closing this issue.
