### ISSUE TITLE
CLI needs a flag which can specify password, but password is not visible on stdout

### ISSUE THREAD

**Issue by rodrigc** [nats-io/natscli#696]
Currently the NATS CLI's `--password` accepts the password as a parameter.
This parameter can be seen in plain text.  On Unix systems, if the user has configured
the shell to retain a history of commands, then
it may be possible to scroll back and see the password passed to the NATS CLI.

There are a few alternatives to using the `--password` flag such as:

• specifying the `NATS_PASSWORD` environment variable
• using `nats context`

However it may be useful to have a flag to the NATS CLI which accepts a password, but the password is not visible on stdout.

In this Slack thread comment:

https://natsio.slack.com/archives/C069GSYFP/p1675417553951759?thread_ts=1674948989.366819&cid=C069GSYFP

 @ripienaar mentioned that it may be possible to add a
`--prompt-password` flag, which instead of taking a password as a parameter which can be seen on stdout,
it forces an interactive prompt and does not echo the output to stdout.

**Comment by rodrigc** [comment]
See also: https://github.com/nats-io/nats.docs/issues/565

**Comment by ripienaar** [comment]
I'll close this, I think prompt password is a very bad solution due to the many times people tend to invoke the command in a row in a session, environment or context is better.
