### ISSUE TITLE
Invalid context JSON causes bad state

### ISSUE THREAD

**Issue by ReubenMathew** [nats-io/natscli#697]
### Description
When editing and saving a `nats context` with invalid JSON (e.g. an extra comma `"url": "nats://127.0.0.1:4222",,`), the cli throws a very generic and unspecific error (e.g. `nats: error: invalid character ',' looking for beginning of object key string`). If one realizes that the issue is a typo in their `<context>.json` file, they are unable to fix it since running `nats context edit` on the affected context will throw the same error. The only solution is to navigate to the directory where the contexts are stored and edit them there, instead of accessing the `.json` config files through the CLI.

Is there a reason why the CLI is validating JSON before allowing the user to edit the context? Also, the resulting error that is thrown is not very descriptive/intuitive.  

### Steps to Reproduce
```
# Create a new context
❯ nats context save new_context

# Edit new context with invalid JSON
❯ nats context edit new_context
# ------ new_context.json ------ #
{
  "description": "",
  "url": "nats://127.0.0.1:4222",, # notice the extra comma
  "token": "",
  "user": "",
}
# ------------------------------- #

# Upon closing and saving your newly edited context, the following error is (expectedly) returned
nats: error: invalid character ',' looking for beginning of object key string

# When trying to reopen the .json file through the cli the same error is thrown
❯ nats context edit new_context
nats: error: invalid character ',' looking for beginning of object key string

# The only way to fix it is to open and edit the file without interacting with the cli
❯ vim ~/.config/nats/context/new_context.json
```
### Local Environment
```
❯ nats --version
0.0.35

❯ system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.1 (22C65)
      Kernel Version: Darwin 22.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Chip: Apple M1 Pro
      Total Number of Cores: 8 (6 performance and 2 efficiency)
      Memory: 16 GB
      System Firmware Version: 8419.60.44
      OS Loader Version: 8419.60.44
```

**Comment by ripienaar** [comment]
There is a fix in the next release to validate before saving which should help

**Comment by ReubenMathew** [comment]
Should it still be validating before you `nats context edit`? What if you edit the context file with a typo through its file path? When you use the CLI to edit again it will throw the error instead of allowing you to edit.

**Comment by ripienaar** [comment]
Will make it not validate before edit

**Comment by ReubenMathew** [comment]
Beautiful! Thanks!
