### ISSUE TITLE
How to search value of multiple keys in key/value store

### ISSUE THREAD

**Issue by smartiniOnGitHub** [nats-io/natscli#702]
Hi all, 
with JetStream Key/value (kv) store, is it possible to do a search (for example via regexp) to get the value of multiple keys inside a bucket ?
Sorry but didn't find info on this and trying the kv get command with wildcards doesn't work.

I'm trying to do something get the value of all keys that matches the given pattern (even a simple one, for example `"*key*"`), like in Redis and with etcd; this would be great.

Just found that with `nats kv ls <sample_kv>` I can list all keys (but only keys) of the given bucket, but didn't find it in documentation.

Thanks a lot. Regards.

**Comment by ripienaar** [comment]
I think the APIs might support this but CLI doesnt.  Any filtering would have to be according to nats wildcard though so no regular expressions.

**Comment by smartiniOnGitHub** [comment]
Hi, thanks for the info; currently CLI doesn't support it; do you think it makes sense to add as a small feature ?
