### ISSUE TITLE
nats subject mapping does not work

### ISSUE THREAD

**Issue by tamalsaha** [nats-io/natscli#703]
I think I have found a bug in nats subject mapping.

```
nats server mapping "ghactions.runs.*.*.*.*" "ghactions.machines.{{wildcard(1)}}.{{wildcard(2)}}.{{partition(3,3,4)}}"

nats: error: invalid mapping destination: not using all of the token wildcard(s) in ghactions.machines.{{wildcard(1)}}.{{wildcard(2)}}.{{partition(3,3,4)}}
```

This should not cause error.

Also, why it is an issue, if I don't want to use all the wildcards in the dest subj?

**Comment by ripienaar** [comment]
I am not sure tbh maybe @jnmoyne knows

**Comment by MauriceVanVeen** [comment]
Seems to be an issue at the server-side.

Specifically in the `newTransform` function, where it throws this error:
```go
if nphs < npwcs {
        // not all wildcards are being used in the destination
	return nil, &mappingDestinationErr{dest, ErrMappingDestinationNotUsingAllWildcards}
}
```

The `{{partition(3,3,4)}}` combines two wildcards, but the code in that function does a `nphs++`, counting the combination of two wildcards in the partition as only one?

**Comment by jnmoyne** [comment]
Currently subject mapping transforms still abide by the rule of "MUST be using all of the partial wildcard tokens defined in the transform's source", which many people have asked about (wanting for that restriction to be removed).

The particular mapping in question should now work once https://github.com/nats-io/nats-server/pull/3887 gets merged in, but I am still working on the relaxing of the overall rule of "must be using all tokens" and will keep this open (unless you want to create an issue specifically about transforms not needing to use all of the partial wildcard tokens in the source in the nats-server repo).
