### ISSUE TITLE
MaxMsgsPerSubject with Int64.MaxValue breaks cli

### ISSUE THREAD

**Issue by m1stegmann** [nats-io/natscli#711]
After creating a stream with "MaxMsgsPerSubject" Int64.MaxValue (C#) the cli returns the following error message for all commands that access streams. Even deleting the stream is then no longer possible via the cli.
The same error message occurs with In64.MaxValue-1

nats stream ls
nats: error: could not list streams: server response is not a valid "io.nats.jetstream.api.v1.stream_list_response" message: missing properties: 'error'
/streams/5/config/max_msgs_per_subject: must be <= 9.223372036854776e+18 but found 9.223372036854776e+18

**Comment by ripienaar** [comment]
Internet max value is indeed bigger than the server technically support (well server does but it’s a number bigger than is valid in JSON and will not work in all languages)

-1 I think is unlimited. You can set environment variable NOVALIDATE=1 to avoid the validation

**Comment by ripienaar** [comment]
I'll close this, there's no reasonable reason to make a stream with `MaxMsgsPerSubject` to max int64, failure could be prettier but this is a bad config.

If anything server/clients should reject this.
