### ISSUE TITLE
server report jetstream does not support json output

### ISSUE THREAD

**Issue by cuberri** [nats-io/natscli#715]
Hi there,

I have configured a jetstream cluster with 3 nodes. According to the documentation, we can use natscli to get a jetstream report formatted as json with the --json flag.

However, json output does not seem to be supported for this specific comand:
```bash
$ nats server report --json jetstream
╭─────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                          JetStream Summary                                          │
├────────┬───────────────┬─────────┬───────────┬──────────┬───────┬────────┬──────┬─────────┬─────────┤
│ Server │ Cluster       │ Streams │ Consumers │ Messages │ Bytes │ Memory │ File │ API Req │ API Err │
├────────┼───────────────┼─────────┼───────────┼──────────┼───────┼────────┼──────┼─────────┼─────────┤
│ nats1  │ local-cluster │ 0       │ 0         │ 0        │ 0 B   │ 0 B    │ 0 B  │ 0       │ 0       │
│ nats3* │ local-cluster │ 0       │ 0         │ 0        │ 0 B   │ 0 B    │ 0 B  │ 0       │ 0       │
│ nats2  │ local-cluster │ 0       │ 0         │ 0        │ 0 B   │ 0 B    │ 0 B  │ 0       │ 0       │
├────────┼───────────────┼─────────┼───────────┼──────────┼───────┼────────┼──────┼─────────┼─────────┤
│        │               │ 0       │ 0         │ 0        │ 0 B   │ 0 B    │ 0 B  │ 0       │ 0       │
╰────────┴───────────────┴─────────┴───────────┴──────────┴───────┴────────┴──────┴─────────┴─────────╯

╭─────────────────────────────────────────────────────────────╮
│                 RAFT Meta Group Information                 │
├───────┬──────────┬────────┬─────────┬────────┬────────┬─────┤
│ Name  │ ID       │ Leader │ Current │ Online │ Active │ Lag │
├───────┼──────────┼────────┼─────────┼────────┼────────┼─────┤
│ nats1 │ RztkeQup │        │ true    │ true   │ 0.02s  │ 0   │
│ nats2 │ SRLRpmYS │        │ true    │ true   │ 0.02s  │ 0   │
│ nats3 │ fvTBnQC7 │ yes    │ true    │ true   │ 0.00s  │ 0   │
╰───────┴──────────┴────────┴─────────┴────────┴────────┴─────
```
It seems to be working well for the other types of report though.

Looks like the command is rendering as a table right away [without considering the json flag](https://github.com/nats-io/natscli/blob/main/cli/server_report_command.go#L175).

**Comment by ripienaar** [comment]
It's not really a documented or stable structure.  So I wouldnt rely on the JSON it might produce.  Suggest you use `nats server req jsz --json` instead

**Comment by ripienaar** [comment]
We definitely 100% do not intend to make that JSON in any way a supported structure.

**Comment by ripienaar** [comment]
For connections report - we do some work to fetch paged results which `req connections` dont support doing, but when you say --json its not dumping the *report* its dumping the connection data it did all the work to gather for you, the connection data is from the server verbatim and under its semver control.

for JSZ there's no paging or anything, so just use `req jsz --json` for the same outcome really

Will close, thank you!

**Comment by justinfx** [comment]
@ripienaar do you agree that it is a bit strange from a UX perspective to provide a `-j, --json` flag in the CLI help, but then only partially implement it for the report subcommands? To me it just seems like another format option of the CLI output. Maybe it is better to just remove the flag altogether, as it doesn't really do what it advertises?

**Comment by ripienaar** [comment]
Fixed in https://github.com/nats-io/natscli/pull/720
