### ISSUE TITLE
NATS CLI not discovering nats server installed on the same docker container

### ISSUE THREAD

**Issue by andronachev** [nats-io/natscli#723]
Hello, 

I am trying to build a dockerFile that will 

1. scaffold the nats:2.9.14-alpine image  
2. install NATS Cli on the same image 
3. run nats and jetstream with custom config

I managed to get the dockerFile working, I can build and install my image with nats cli in it as well as nats-server... but nats cli keeps saying **nats: error: setup failed: nats: no servers available for connection**

On the other hand if I raise another docker container with the standalone nats-box image which has nats cli installed ,it is discovering my nats server that's running in my image. 

My docker file:

```
FROM nats:2.9.14-alpine

COPY nats-streaming-server.conf /etc/nats/nats-streaming-server.conf

# install GO 
RUN apk add --no-cache git make musl-dev go

ENV GOROOT /usr/lib/go
ENV GOPATH /go
ENV PATH /go/bin:$PATH

RUN mkdir -p ${GOPATH}/src ${GOPATH}/bin

ENV NATS_CONFIG_HOME=/etc/nats/

RUN  mkdir -p /usr/local/bin

# install same tools as installed in the nats box... not sure which ones are needed, suppose only natscli but I unstalled them all to be sure
RUN go install github.com/nats-io/natscli/nats@latest
RUN go install -ldflags="-X main.version=@latest" github.com/nats-io/nsc/v2@latest
RUN go install github.com/nats-io/nats-top@latest
RUN go install github.com/nats-io/natscli/nats@latest
RUN go install github.com/nats-io/stan.go/examples/stan-pub@latest
RUN go install github.com/nats-io/stan.go/examples/stan-sub@latest
RUN go install github.com/nats-io/stan.go/examples/stan-bench@latest

#commands coppied from the nats-box docker file to try  to make the nats cli work ... 
RUN set -e
RUN addgroup -g 1000 nats
RUN adduser -D -u 1000 -G nats nats
RUN apk add -U --no-cache ca-certificates curl figlet jq
ENV NKEYS_PATH /nsc/nkeys
ENV XDG_DATA_HOME /nsc
ENV XDG_CONFIG_HOME /nsc/.config

EXPOSE 8080 8222 6222 

ENTRYPOINT ["nats-server", "-c", "/etc/nats/nats-streaming-server.conf", "-js"]
CMD []

```

the conf file: 

```
# Client port of 4222 on all interfaces
port: 8080

# HTTP monitoring port
monitor_port: 8222

max_payload: 10485760
server_name:test-server
jetstream {
    store_dir: nats
    max_file_store: 2G
}
```

Do you maybe have any pointers ? I am surprised by the way that I haven't found an out of the box nats image that also contains the NATS CLI. 

The reason I want to have NATS CLI in the same container is to have jetstream management (want to be able ot create a stream from the docker file)... so that is the next step and goal, automatic Stream creation from the docker file.

Thank you

**Comment by ripienaar** [comment]
you're not saying how you run the nats command - by default it tries localhost:4222, but you're setting it to 8080.

**Comment by andronachev** [comment]
> you're not saying how you run the nats command - by default it tries localhost:4222, but you're setting it to 8080.

Just after the container started, tried "nats str ls" and received "no server available for connection". 
But indeed I removed the 8080 setting and restored to default 4222 and it workd after. Thank you
