### ISSUE TITLE
Allow various report commands to target a specific server

### ISSUE THREAD

**Issue by ripienaar** [nats-io/natscli#754]

**Comment by ripienaar** [comment]
The various `nats server report ...` commands now take `--host`, `--cluster` and `--tags` (can be supplied multiple times) to filter the reports on various dimensions.

//cc @derekcollison

**Comment by derekcollison** [comment]
Very nice, I specifically need it to connect to a specific IP with a hostname for TLS since that IP is not in the cert.

This is for debugging asymmetric behaviors in ssystems.

**Comment by ripienaar** [comment]
> Very nice, I specifically need it to connect to a specific IP with a hostname for TLS since that IP is not in the cert.
> 
> This is for debugging asymmetric behaviors in ssystems.

Yeah I opened a issue to implement that - but nats.go has no option to enable that.  So need to do custom tlsc I guess, bit more work unless we add something to nats.go
