### ISSUE TITLE
translate feature not surfaced yet ?

### ISSUE THREAD

**Issue by gedw99** [nats-io/natscli#761]
is it surfaced on the cli yet ?

https://github.com/metatexx/msgcvt/issues/1#issue-1672678618

**Comment by ripienaar** [comment]
The next CLI release will be around nats server 2.10 time unfortunately

You can try the cli in docker container `synadia/nats-server:nightly` which would have it.

**Comment by oderwat** [comment]
We just install it with `go install github.com/nats-io/natscli/nats@main`
