### ISSUE TITLE
Specifying --names should request .NAMES instead of .LIST

### ISSUE THREAD

**Issue by jarretlavallee** [nats-io/natscli#778]
`nats stream ls --names` currently queries `$JS.API.STREAM.LIST`, which gathers more information than `$JS.API.STREAM.NAMES`. `$JS.API.STREAM.NAMES` should be instant and has the required information to fulfill the request. Please change any instance of the `--names` parameter to use the `.NAMES` instead of `.LIST`.

**Comment by ripienaar** [comment]
Fixed in https://github.com/nats-io/natscli/pull/779
