### ISSUE TITLE
UX: easy to create a push-mode consumer pushing to subject pull

### ISSUE THREAD

**Issue by philpennock** [nats-io/natscli#78]
Someone using this nats CLI tried to create a pull-mode consumer on a stream, and when asked for the `Delivery target` they typed in the word `pull`.

Hey presto, a push-mode consumer pushing to NATS subject `pull`.

The only currently supported way of entering this, AFAIK, is to instead just hit enter for an empty target.  I only "remembered" this because when prompted for the target, I'd entered `?` and read the help text.

Perhaps we should have a case-insensitive comparison of the string against `pull` and insert a "hey, are you sure?" question; or, if we don't want to affect scriptability here, just throw up a big "WARNING: foo" message in this scenario.

**Comment by ripienaar** [comment]
I am not really a fan of the confirmation approach, another way is to add —pull and it won’t ask the subject. 

Alternatively I can expand the question text with like (empty for pull consumers) or similar.

**Comment by philpennock** [comment]
Avoiding the confirmation: sounds good.  The issue with `--pull` is discoverability of UX.
Expanding the question text might help.
I think that detecting `pull` as a push topic is worth doing, and just putting up `WARNING: you have chosen to push to a topic named 'pull'; if not desired outcome, try again with '--pull' or leave topic empty` before showing the next question.

**Comment by ripienaar** [comment]
Closed by https://github.com/nats-io/natscli/pull/79
