### ISSUE TITLE
Feature: publish protocol for stdin, sockets and pipes 

### ISSUE THREAD

**Issue by Zetanova** [nats-io/natscli#781]
The nats-cli could be used to add support for legacy apps and system hooks.

I would need to be extended with a simple streaming protocol to accept multiple messages
from stdin, socket file or win-pipe

The simple protocol could be used to set the subject and headers beside the payload.

It would reduce the connection overhead for frequent messaging,
make it possible create the connection from a priviligated user context.

### Socket Examble

UserA:
```
nats --server=nats://natsserver --creds=mycredsfile --tlsca=thecapem pub --socket=/tmp/nats.sock
```

UserB:
```
socat UNIX-CLIENT:/tmp/nats.sock - <<EOF 
thesubject.test1
header1: value1

<binary>
EOF

socat UNIX-CLIENT:/tmp/nats.sock - <<EOF 
thesubject.test2
header1: value2

<binary>
EOF
```

### Pipe Examble

UserA:
```
nats --server=nats://natsserver --creds=mycredsfile --tlsca=thecapem pub --pipe=/tmp/nats.pub
```

UserB:
```
/tmp/nats.pub <<EOF 
thesubject.test1
header1: value1

<binary>
EOF

/tmp/nats.pub <<EOF 
thesubject.test2
header1: value2

<binary>
EOF
```

### stdin examble
```
nats --server=nats://natsserver --creds=mycredsfile --tlsca=thecapem pub --stdin <<EOF 
thesubject.test1
header1: value1

<binary>
\0
thesubject.test2
header1: value2

<binary>
EOF
```

**Comment by Zetanova** [comment]
Would be good to define/set the message stream protocol here. 

Wanted to write a message from inside an old MTA `exim4`,
its a little bit heavy to spool up nats-cli and a connection 
for each mail.

**Comment by ripienaar** [comment]
I hear you - but conceptionally CLI isnt eventing anything, we take tools and protocols and libraries that exist and wrap them in a UX.

So I am reluctant to pivot to deisning things.

What I can maybe mention is that the CLI will soon (already in main in some form) be able to take plugins.  You, or NATS community, could write `nats bridge` as a plugin.

The focus here in this project is pretty much to offer UX around existing things.

**Comment by ripienaar** [comment]
Will close this one for now as I still think its out of scope.  Maybe a community plugin could be done for this and used to extend the CLI.
