### ISSUE TITLE
`nats bench` creates R1 consumer for R3 stream

### ISSUE THREAD

**Issue by goku321** [nats-io/natscli#783]
Expected:
`nats bench bar --js --pub 1 --sub 1 --size 128 --storage=file --replicas 3` should create R3 consumers instead of R1

Actual:
`nats bench` creates R1 consumers for R3 stream

**Comment by ripienaar** [comment]
I believe it's using a ordered consumer in this case which are ephemeral - those are always R1.

passing `--push` looks like it will then create a durable which is R3

**Comment by goku321** [comment]
@ripienaar Thanks for your reply. I tried with `--pull` and it works as expected.
