### ISSUE TITLE
Windows json issue

### ISSUE THREAD

**Issue by dpalat** [nats-io/natscli#817]
Hello, there is a issue publishing a messages with json using the CLI for windows but works perfect using the compilation for Linux,
you can reproduce using this two commands.

**Pub:** 
 nats --server=http://localhost:4222 pub DOMAIN.events.testing.01 '{"UserId":"jane_doe_user_001","CountryCode":"AR"}'
**Sub:**
 nats --server=http://localhost:4222 consumer next DOMAIN DOMAIN_messages
 
 result of consumer next in **Windows**: {UserId:jane_doe_user_001,CountryCode:AR}  _INVALID JSON_ ❌
 result of consumer next in **Ubuntu**: {"UserId":"jane_doe_user_001","CountryCode":"AR"}  _VALID JSON_  ✅

nats --version 0.0.35 in both, Windows and Ubuntu.

Test using Windows cli
![image](https://github.com/nats-io/natscli/assets/2325020/e1c13f06-2151-44c1-ad91-f39faaeb7850)

Test using linux cli
![image](https://github.com/nats-io/natscli/assets/2325020/f8dd2795-ffe0-4dfb-8102-171535f730f0)

Thanks !!

**Comment by ripienaar** [comment]
This is likely down to how the windows shell handles quotes - the nats cli does not try to interpret the input, it takes it as given.  So I would guess these quotes would need windows specific escapes on your command line.

**Comment by dpalat** [comment]
Thank you for your response, @ripienaar.

In my opinion, I believe it would be better if the Windows CLI could handle this simple JSON string instead of adding more complexity for Windows users when attempting to send it. Perhaps the parsing issue in the CLI could be fixed without any escapes character.

I suggest keeping this as an issue specifically for the Windows version of the NATS CLI.

**Comment by ripienaar** [comment]
As I explained, the nats cli does not parse the JSON.  It's about how you enter the JSON in your command prompt.  Windows is parsing it prior to passing the messages to the nats CLI, in other words, before I can do anything about it.

**Comment by ripienaar** [comment]
On windows terminal or powersehll terminal you must quote JSON like this, `"{\"x\":\"y\"}"`, that's just how windows works.  I cannot fix windows for you.
