### ISSUE TITLE
Unable to edit context when last saved context contain errors

### ISSUE THREAD

**Issue by atlejensen** [nats-io/natscli#844]
If you wrongfully edit a context and make it invalid, it is not possible to correct the error using "nats context edit <context-name>". The command only prompts with an error and exit.
Example:
{
  "description": "My-NATS",
  "url": "nats://localhost:4222",
  "token": "",
  "user": "user",
  "password": ""mySuperSecretPasswordEnteredTheWrongPlace,
  "creds": "",
  "nkey": "",
  "cert": "",
  "key": "",
  "ca": "",
  "nsc": "",
  "jetstream_domain": "",
  "jetstream_api_prefix": "",
  "jetstream_event_prefix": "",
  "inbox_prefix": "",
  "user_jwt": ""
}

Will give an error: "nats: error: invalid character 'm' after object key:value pair"

Workaround is to edit the JSON file directly to fix the typo.

My environment:
Editor: vim
Shell: zsh 5.9 (x86_64-apple-darwin22.0)
NATS CLI version: 0.0.35

**Comment by ripienaar** [comment]
This is fixed in the nightly builds tjst will release in the next few weeks
