### ISSUE TITLE
nats micro reporting service response times in 2 different units

### ISSUE THREAD

**Issue by autodidaddict** [nats-io/natscli#880]
### What version were you using?

NATS CLI v0.1.1

### What environment was the server running in?

Ubuntu 

### Is this defect reproducible?

Yes. Make a few calls to any service and the line items will be in microseconds while the summary total is in milliseconds

### Given the capability you are leveraging, describe your expectation?

I would expect the unit of measurement to be consistent between the line items and summary

### Given the expectation, what is the defect you are observing?

It's using `MS` as the label for the summary when it should be using `9µs`

```
nats micro stats GameAggregateCommand
╭────────────────────────────────────────────────────────────────────────────────────────╮
│                         GameAggregateCommand Service Statistics                        │
├────────────────────────┬──────────┬──────────┬────────┬─────────────────┬──────────────┤
│ ID                     │ Endpoint │ Requests │ Errors │ Processing Time │ Average Time │
├────────────────────────┼──────────┼──────────┼────────┼─────────────────┼──────────────┤
│ jUjoIhIHAxh2yyqC3Wmohh │ default  │ 4        │ 0      │ 35µs            │ 9µs          │
├────────────────────────┼──────────┼──────────┼────────┼─────────────────┼──────────────┤
│                        │          │ 4        │ 0      │ 35ΜS            │ 9ΜS          │
╰────────────────────────┴──────────┴──────────┴────────┴─────────────────┴──────────────╯
```

**Comment by ripienaar** [comment]
Apparently a bug in the table rendering library, will open upstream

https://go.dev/play/p/Sz5YtCn9Bol

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/882 table rendered was doing to upper on the strings in the footer and somehow turning micro to M.

Prevented the upcasing - which I hated anyway.
