### ISSUE TITLE
v0.1.1 release is broken without any binaries

### ISSUE THREAD

**Issue by alexellis** [nats-io/natscli#887]
### What version were you using?

v0.1.0

### What environment was the server running in?

arkade

https://github.com/alexellis/arkade/actions/runs/6350196448

```
=== NAME  Test_CheckTools/Download_of_nats
    url_checker_test.go:51: Error with HTTP HEAD for nats, https://github.com/nats-io/natscli/releases/download/v0.1.1/nats-0.1.1-linux-amd64.zip: status code: 404, body: 
```

### Is this defect reproducible?

Yes

### Given the capability you are leveraging, describe your expectation?

Each of the hundreds of CLI tools we support on arkade have binaries attached to every release on GitHub, this is a standard practice and should be done here also.

### Given the expectation, what is the defect you are observing?

Upload the binaries to the release so that nats can continue to be offered via `arkade get`

**Comment by ripienaar** [comment]
As the release notes indicate the 0.1.1 release only really fixed `go install` so we didnt do all the binaries, update brew etc.

Next release isnt far away so that will have binaries again.

**Comment by alexellis** [comment]
How soon?

This is going to break every CI job for people using arkade to get the NATS cli, including any additional scripts that people are using within installers etc. How much trouble is it for you to upload binaries? I have it automated for all the projects I maintain

**Comment by ripienaar** [comment]
We release when ready, but not long. I am glad you have it automated.
