### ISSUE TITLE
natscli invoking external editors could use valid extensions for temporary file names - hint for color highlighting in editor

### ISSUE THREAD

**Issue by borjaetxebarria** [nats-io/natscli#902]
### Proposed change

Right now the files have a random name with no extension, so the external editor does not color json content. 
It would be nice if the temp file had a .json extension, that way files would be easier to read in editors that support color highlighting based on file extension.   

### Use case

Would make files easier to read, specially as there are so many comments interleaved with configuration values.

**Comment by ripienaar** [comment]
Done in https://github.com/nats-io/natscli/pull/903
