### ISSUE TITLE
Flag --names ineffective for listing objects inside a bucket as a plain list

### ISSUE THREAD

**Issue by Alfablos** [nats-io/natscli#907]
### Observed behavior

`nats object ls --names mybucket` still shows a table.

### Expected behavior

`nats object ls --names mybucket` shows a plain list of object names

### Server and client version

nats-server: v2.10.1 | 2.10.2 | v2.10.3
nats-client: 0.1.1 |  (devel) (AUR)

### Host environment

- EndeavourOS (Arch) + Nix
- Garuda (Arch)

### Steps to reproduce

```
nats-server -js
nats object add images
nats object put images ~/Downloads/desert-doom-sand-dunes-dark-background-monochrome-landscape-3840x2160-6409.jpg
nats object ls
nats object ls --names        # Ok!
nats object ls images         # Table: ok!
nats object ls --names images    # Table: not ok :(
```
![nats-names-issue_obscured](https://github.com/nats-io/natscli/assets/46743630/2045fc7a-54f1-42ee-ae73-a310fa221791)

**Comment by ripienaar** [comment]
Resolved in https://github.com/nats-io/natscli/pull/908 thanks for the report
