### ISSUE TITLE
nats account report connections should support reverse sorting the output

### ISSUE THREAD

**Issue by protochron** [nats-io/natscli#935]
### Proposed change

`nats account report connections` should have a `-R/--reverse` flag added so that you can reverse sort the output. It should work the same way that `nats server report connections` does.

### Use case

Being able to reverse sort the output makes it a lot easier to spot the most active accounts. Scrolling to the bottom of the list or trying to do so using the raw json output is a pain.

**Comment by ripienaar** [comment]
Done for next release https://github.com/nats-io/natscli/pull/945
