### ISSUE TITLE
Context subcommand "create" missing from CLI Menu

### ISSUE THREAD

**Issue by ramantehlan** [nats-io/natscli#976]
### Observed behaviour

Nats docs mention the[ `context create` command](https://docs.nats.io/using-nats/nats-tools/nats_cli#nats-contexts:~:text=A%20context%20can%20be%20created%20with%20nats%20context%20create%20my_context_namehttps://docs.nats.io/using-nats/nats-tools/nats_cli#nats-contexts:~:text=A%20context%20can%20be%20created%20with%20nats%20context%20create%20my_context_name), and it works too. However, it's not part of the subcommand menu.

![image](https://github.com/nats-io/natscli/assets/29037312/9528f02d-bb4b-4551-b3d3-1fdcc22fe85f)

### Expected behaviour

It should be part of it, so when someone looking for help in CLI, can find it, and use it. 

### Server and client version

nats-server: v2.10.9
nats: 0.1.1

### Host environment

```
OS: Ubuntu 22.04.3 LTS x86_64
Host: 20L5S08M00 ThinkPad T480
Shell: zsh 5.8.1
CPU: Intel i7-8550U (8) @ 4.000GHz
GPU: Intel UHD Graphics 620
GPU: NVIDIA GeForce MX150
Memory: 15185MiB / 31846MiB
```

### Steps to reproduce

Run the command `nats context -h`. It will give a subcommand, but it won't have the `create`.

### Checks

- [x] Did you check for duplicate issues?

---

PS: I am not aware if the team decided to leave this command out of help on purpose. I did try to search for any reference to that, but couldn't.

**Comment by ripienaar** [comment]
Many commands have aliases. Some like typing add. Some save and some create or new. So I add aliases. Help only shows the main one - save in this case.

**Comment by ramantehlan** [comment]
Got it, thanks!
