### ISSUE TITLE
sub: allow multiple subjects

### ISSUE THREAD

**Issue by philpennock** [nats-io/natscli#982]
### Proposed change

Rather than `nats sub` taking one single subject, it should take one-or-more subjects, and setup subscribers on all of them, displaying the results as a single stream.

For sanity, is probably reasonable to impose an arbitrary limit of N subscriptions, where N might be 16 or so.  I don't see myself wanting more than 3 at once.

### Use case

Debugging what's going on by watching 2 or 3 distinct subject hierarchies of interest.

### Contribution

Sure, can do.

**Comment by ripienaar** [comment]
https://github.com/nats-io/natscli/pull/983
