### ISSUE TITLE
Consider making a new release

### ISSUE THREAD

**Issue by paolobarbolini** [nats-io/natscli#984]
### Proposed change

Consider making a new GitHub release

### Use case

Getting the following changes out and into distros
https://github.com/nats-io/natscli/compare/v0.1.1...main

**Comment by ripienaar** [comment]
We might make a point release but right now we have a bunch of inflight work - both in PRs and what I know is incoming - so we're waiting for those to settle down a bit.

But yeah we might make a point release for some bug fixes, but not a lot of new features would land there

**Comment by paolobarbolini** [comment]
Is see v0.1.3 is out. That fixes it for me. I was mainly looking at TLS first and the other fixes :+1:
I see Arch already picked up the new version.
